# Netlify configuration for Efficiency Life Flight

[build]
  publish = "dist"

[[redirects]]
  from = "https://efficiencylife-flight.netlify.app/*"
  to = "https://efficiency-life.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://efficiencylife-flight.netlify.app/*"
  to = "https://efficiency-life.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.efficiency-life.com/*"
  to = "https://efficiency-life.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.efficiency-life.com/*"
  to = "https://efficiency-life.com/:splat"
  status = 301
  force = true
