/* EFFICIENCY LIFE — FLIGHT · lingue e valute
   ------------------------------------------------------------------
   L'interfaccia (etichette, pulsanti, intestazioni) e' tradotta in 36
   lingue: coprono circa cinque miliardi e mezzo di parlanti e tutti i
   mercati di partenza serviti dall'indice. I testi lunghi del capitolo
   "Metodo" e "Trasparenza" restano in italiano e inglese, con l'inglese
   come ripiego: meglio un paragrafo in inglese che una traduzione
   automatica di cui nessuno risponde.
   I nomi di paesi, lingue e valute non sono in queste tabelle: li
   fornisce Intl.DisplayNames del browser, nella lingua scelta.
   4.09.2026 — rilettura riga per riga di tutte le 36 lingue. Le voci
   aggiunte con la forma del viaggio e lo scarto dal prezzo atteso non
   ricadono piu' sull'inglese: adesso ogni lingua ha tutte le chiavi.  */

/* ordine delle chiavi: ogni lingua e' un array parallelo a questo */
const KEYS = ['nav_search','nav_method','nav_priv','share','copied','day','night','platform','soon',
 'st_air','st_dest','st_fare','st_best','f_from','f_continent','f_country','f_airport','f_all','f_clear',
 'f_selected','f_to','f_anywhere','f_globe','f_when','f_window','f_window_h','f_dist','f_budget','f_bag',
 'f_currency','f_language','f_searchph','btn_search','b_found','b_sort','th_route','th_price','th_dist',
 'th_stay','th_score','th_check','nights','rt','eachway','direct','copylink','empty_t','empty_b',
 'everywhere','more','obs','h1a','h1b',
 'r_eu','r_as','r_me','r_na','r_la','r_af','r_oc',
 'f_need','f_dirty','book','stay','act',
 'f_shape','sh_any','sh_long','sh_mid','sh_short','th_deal','deal_u','hist_low','hist_med'];

const LANGS = {
en:['Search','Method','Transparency','Share','Copied','Day','Night','Platform','Coming soon','Departure airports','Destinations','Verified fares','Best ratio','Departure','Continent','Country','Airport','All','Clear','selected','Destination','Anywhere','Spin the globe, tap a country','When','Days to departure','How many days from today until you fly — pick one band or several.','Maximum distance','Maximum budget','Checked bag','Currency','Language','Search a country or airport','Search','Routes found','Sort by','Route','Price','Distance','Stay','Score','Verify','nights','return','each way','Direct','Copy link','No fare matches these filters','Widen the day range or drop a filter','Anywhere from','Show all','Observed','Stop choosing where.','Choose how far.','Europe','Asia','Middle East','North America','Latin America','Africa','Oceania','Pick at least one departure airport','Filters changed — press Search','Book','Hotels','Things to do','Trip shape','Any','Long weekend · Fri→Mon','Weekend · Fri→Sun','Quick trip · Sat→Sun','Deal','vs expected','lowest 10%','below median'],
it:['Ricerca','Metodo','Trasparenza','Condividi','Copiato','Giorno','Notte','Piattaforma','In arrivo','Aeroporti di partenza','Destinazioni','Tariffe verificate','Miglior rapporto','Partenza','Continente','Paese','Aeroporto','Tutti','Azzera','selezionati','Destinazione','Ovunque','Ruota il globo, tocca un paese','Quando','Giorni alla partenza','Fra quanti giorni parti, contati da oggi. Puoi scegliere più intervalli.','Distanza massima','Budget massimo','Bagaglio in stiva','Valuta','Lingua','Cerca un paese o un aeroporto','Cerca','Rotte trovate','Ordina per','Rotta','Prezzo','Distanza','Soggiorno','Punteggio','Verifica','notti','andata e ritorno','a tratta','Diretto','Copia link','Nessuna tariffa con questi filtri','Allarga l’intervallo di giorni o togli un filtro','Ovunque da','Mostra tutte','Rilevate il','Non scegliere dove.','Scegli quanto lontano.','Europa','Asia','Medio Oriente','Nord America','America Latina','Africa','Oceania','Scegli almeno un aeroporto di partenza','Filtri cambiati — premi Cerca','Prenota','Hotel','Attività','Forma del viaggio','Qualsiasi','Weekend lungo · ven→lun','Weekend · ven→dom','Mordi e fuggi · sab→dom','Affare','sul prezzo atteso','nel 10% più basso','sotto la mediana'],
es:['Búsqueda','Método','Transparencia','Compartir','Copiado','Día','Noche','Plataforma','Próximamente','Aeropuertos de salida','Destinos','Tarifas verificadas','Mejor relación','Salida','Continente','País','Aeropuerto','Todos','Borrar','seleccionados','Destino','A cualquier parte','Gira el globo y toca un país','Cuándo','Días hasta la salida','Cuántos días faltan para volar, contados desde hoy. Puedes elegir varios tramos.','Distancia máxima','Presupuesto máximo','Equipaje facturado','Moneda','Idioma','Busca un país o aeropuerto','Buscar','Rutas encontradas','Ordenar por','Ruta','Precio','Distancia','Estancia','Puntuación','Verificar','noches','ida y vuelta','por trayecto','Directo','Copiar enlace','Ninguna tarifa con estos filtros','Amplía el intervalo de días o quita un filtro','A cualquier parte desde','Ver todas','Observado el','Deja de elegir adónde.','Elige cuán lejos.','Europa','Asia','Oriente Medio','América del Norte','América Latina','África','Oceanía','Elige al menos un aeropuerto de salida','Filtros cambiados: pulsa Buscar','Reservar','Hoteles','Actividades','Forma del viaje','Cualquiera','Finde largo · vie→lun','Fin de semana · vie→dom','Escapada · sáb→dom','Oferta','sobre el precio esperado','en el 10% más bajo','bajo la mediana'],
fr:['Recherche','Méthode','Transparence','Partager','Copié','Jour','Nuit','Plateforme','Bientôt','Aéroports de départ','Destinations','Tarifs vérifiés','Meilleur rapport','Départ','Continent','Pays','Aéroport','Tous','Effacer','sélectionnés','Destination','Partout','Faites tourner le globe, touchez un pays','Quand','Jours avant le départ','Dans combien de jours vous partez, à compter d’aujourd’hui. Plusieurs plages possibles.','Distance maximale','Budget maximal','Bagage en soute','Devise','Langue','Chercher un pays ou un aéroport','Rechercher','Itinéraires trouvés','Trier par','Itinéraire','Prix','Distance','Séjour','Score','Vérifier','nuits','aller-retour','par trajet','Direct','Copier le lien','Aucun tarif avec ces filtres','Élargissez la plage de jours ou retirez un filtre','Partout au départ de','Tout afficher','Relevé le','Ne choisissez plus où.','Choisissez jusqu’où.','Europe','Asie','Moyen-Orient','Amérique du Nord','Amérique latine','Afrique','Océanie','Choisissez au moins un aéroport de départ','Filtres modifiés — appuyez sur Rechercher','Réserver','Hôtels','Activités','Forme du voyage','Indifférent','Week-end prolongé · ven→lun','Week-end · ven→dim','Escapade · sam→dim','Écart','vs prix attendu','dans les 10% les plus bas','sous la médiane'],
de:['Suche','Methode','Transparenz','Teilen','Kopiert','Tag','Nacht','Plattform','Demnächst','Abflughäfen','Ziele','Geprüfte Tarife','Bestes Verhältnis','Abflug','Kontinent','Land','Flughafen','Alle','Zurücksetzen','ausgewählt','Ziel','Überallhin','Globus drehen, Land antippen','Wann','Tage bis zum Abflug','In wie vielen Tagen Sie fliegen, ab heute gezählt. Mehrere Bereiche möglich.','Maximale Entfernung','Maximales Budget','Aufgabegepäck','Währung','Sprache','Land oder Flughafen suchen','Suchen','Gefundene Strecken','Sortieren nach','Strecke','Preis','Entfernung','Aufenthalt','Punktzahl','Prüfen','Nächte','Hin und zurück','pro Strecke','Direkt','Link kopieren','Kein Tarif passt zu diesen Filtern','Tagesbereich erweitern oder Filter entfernen','Überallhin ab','Alle anzeigen','Erfasst am','Hören Sie auf, das Wohin zu wählen.','Wählen Sie das Wie weit.','Europa','Asien','Naher Osten','Nordamerika','Lateinamerika','Afrika','Ozeanien','Wählen Sie mindestens einen Abflughafen','Filter geändert — auf Suchen drücken','Buchen','Hotels','Aktivitäten','Reiseform','Beliebig','Langes Wochenende · Fr→Mo','Wochenende · Fr→So','Kurztrip · Sa→So','Abweichung','vs. erwartetem Preis','unter den 10% günstigsten','unter dem Median'],
pt:['Pesquisa','Método','Transparência','Partilhar','Copiado','Dia','Noite','Plataforma','Em breve','Aeroportos de partida','Destinos','Tarifas verificadas','Melhor relação','Partida','Continente','País','Aeroporto','Todos','Limpar','selecionados','Destino','Para qualquer lugar','Gire o globo e toque num país','Quando','Dias até à partida','Daqui a quantos dias parte, contados a partir de hoje. Pode escolher vários intervalos.','Distância máxima','Orçamento máximo','Bagagem de porão','Moeda','Idioma','Procurar país ou aeroporto','Pesquisar','Rotas encontradas','Ordenar por','Rota','Preço','Distância','Estadia','Pontuação','Verificar','noites','ida e volta','por trecho','Direto','Copiar ligação','Nenhuma tarifa com estes filtros','Alargue o intervalo de dias ou retire um filtro','Para qualquer lugar a partir de','Mostrar todas','Observado em','Pare de escolher para onde.','Escolha quão longe.','Europa','Ásia','Médio Oriente','América do Norte','América Latina','África','Oceania','Escolha pelo menos um aeroporto de partida','Filtros alterados — prima Pesquisar','Reservar','Hotéis','Atividades','Forma da viagem','Qualquer','Fim de semana longo · sex→seg','Fim de semana · sex→dom','Escapadinha · sáb→dom','Desconto','face ao preço esperado','nos 10% mais baixos','abaixo da mediana'],
nl:['Zoeken','Methode','Transparantie','Delen','Gekopieerd','Dag','Nacht','Platform','Binnenkort','Vertrekluchthavens','Bestemmingen','Geverifieerde tarieven','Beste verhouding','Vertrek','Continent','Land','Luchthaven','Alle','Wissen','geselecteerd','Bestemming','Overal heen','Draai de globe, tik op een land','Wanneer','Dagen tot vertrek','Over hoeveel dagen u vertrekt, geteld vanaf vandaag. U kunt meerdere reeksen kiezen.','Maximale afstand','Maximaal budget','Ruimbagage','Valuta','Taal','Zoek een land of luchthaven','Zoeken','Gevonden routes','Sorteren op','Route','Prijs','Afstand','Verblijf','Score','Controleren','nachten','retour','per traject','Direct','Link kopiëren','Geen tarief met deze filters','Verruim het aantal dagen of verwijder een filter','Overal heen vanaf','Alles tonen','Waargenomen op','Kies niet langer waarheen.','Kies hoe ver.','Europa','Azië','Midden-Oosten','Noord-Amerika','Latijns-Amerika','Afrika','Oceanië','Kies minstens één vertrekluchthaven','Filters gewijzigd — druk op Zoeken','Boeken','Hotels','Activiteiten','Reisvorm','Alles','Lang weekend · vr→ma','Weekend · vr→zo','Kort tripje · za→zo','Korting','t.o.v. verwachte prijs','in de laagste 10%','onder de mediaan'],
sv:['Sök','Metod','Öppenhet','Dela','Kopierad','Dag','Natt','Plattform','Kommer snart','Avreseflygplatser','Destinationer','Verifierade priser','Bästa förhållandet','Avresa','Kontinent','Land','Flygplats','Alla','Rensa','valda','Destination','Vart som helst','Snurra jordgloben, tryck på ett land','När','Dagar till avresa','Om hur många dagar du reser, räknat från idag. Du kan välja flera intervall.','Största avstånd','Högsta budget','Incheckat bagage','Valuta','Språk','Sök land eller flygplats','Sök','Hittade rutter','Sortera efter','Rutt','Pris','Avstånd','Vistelse','Poäng','Kontrollera','nätter','tur och retur','per sträcka','Direkt','Kopiera länk','Inget pris matchar filtren','Vidga dagintervallet eller ta bort ett filter','Vart som helst från','Visa alla','Noterat den','Sluta välja vart.','Välj hur långt.','Europa','Asien','Mellanöstern','Nordamerika','Latinamerika','Afrika','Oceanien','Välj minst en avreseflygplats','Filtren ändrade — tryck på Sök','Boka','Hotell','Aktiviteter','Resans form','Alla','Långhelg · fre→mån','Helg · fre→sön','Snabbresa · lör→sön','Fynd','mot förväntat pris','bland de 10% lägsta','under medianen'],
da:['Søg','Metode','Gennemsigtighed','Del','Kopieret','Dag','Nat','Platform','Kommer snart','Afgangslufthavne','Destinationer','Bekræftede priser','Bedste forhold','Afgang','Kontinent','Land','Lufthavn','Alle','Ryd','valgte','Destination','Overalt','Drej kloden, tryk på et land','Hvornår','Dage til afgang','Om hvor mange dage du rejser, talt fra i dag. Du kan vælge flere intervaller.','Maksimal afstand','Maksimalt budget','Indchecket bagage','Valuta','Sprog','Søg land eller lufthavn','Søg','Fundne ruter','Sortér efter','Rute','Pris','Afstand','Ophold','Score','Kontrollér','nætter','tur/retur','pr. strækning','Direkte','Kopiér link','Ingen pris med disse filtre','Udvid dagintervallet eller fjern et filter','Overalt fra','Vis alle','Registreret den','Hold op med at vælge hvorhen.','Vælg hvor langt.','Europa','Asien','Mellemøsten','Nordamerika','Latinamerika','Afrika','Oceanien','Vælg mindst én afgangslufthavn','Filtre ændret — tryk på Søg','Book','Hoteller','Oplevelser','Rejsens form','Alle','Lang weekend · fre→man','Weekend · fre→søn','Kort tur · lør→søn','Fund','mod forventet pris','blandt de 10% laveste','under medianen'],
no:['Søk','Metode','Åpenhet','Del','Kopiert','Dag','Natt','Plattform','Kommer snart','Avreiseflyplasser','Destinasjoner','Bekreftede priser','Beste forhold','Avreise','Kontinent','Land','Flyplass','Alle','Nullstill','valgte','Destinasjon','Overalt','Snurr kloden, trykk på et land','Når','Dager til avreise','Om hvor mange dager du reiser, regnet fra i dag. Du kan velge flere intervaller.','Største avstand','Høyeste budsjett','Innsjekket bagasje','Valuta','Språk','Søk land eller flyplass','Søk','Ruter funnet','Sorter etter','Rute','Pris','Avstand','Opphold','Poeng','Sjekk','netter','tur-retur','per strekning','Direkte','Kopier lenke','Ingen pris med disse filtrene','Utvid dagintervallet eller fjern et filter','Overalt fra','Vis alle','Registrert','Slutt å velge hvor.','Velg hvor langt.','Europa','Asia','Midtøsten','Nord-Amerika','Latin-Amerika','Afrika','Oseania','Velg minst én avreiseflyplass','Filtrene er endret — trykk Søk','Bestill','Hoteller','Aktiviteter','Reisens form','Alle','Lang helg · fre→man','Helg · fre→søn','Kort tur · lør→søn','Funn','mot forventet pris','blant de 10% laveste','under medianen'],
fi:['Haku','Menetelmä','Läpinäkyvyys','Jaa','Kopioitu','Päivä','Yö','Alusta','Tulossa','Lähtökentät','Kohteet','Vahvistetut hinnat','Paras suhde','Lähtö','Manner','Maa','Lentoasema','Kaikki','Tyhjennä','valittu','Kohde','Minne tahansa','Pyöritä palloa, napauta maata','Milloin','Päiviä lähtöön','Monenko päivän päästä lähdet, tästä päivästä laskien. Voit valita useita jaksoja.','Enimmäisetäisyys','Enimmäisbudjetti','Ruumaan menevä laukku','Valuutta','Kieli','Hae maata tai lentoasemaa','Hae','Löytyneet reitit','Järjestä','Reitti','Hinta','Etäisyys','Oleskelu','Pisteet','Tarkista','yötä','meno-paluu','yhteen suuntaan','Suora','Kopioi linkki','Ei hintoja näillä suodattimilla','Laajenna päiväväliä tai poista suodatin','Minne tahansa lähtien','Näytä kaikki','Havaittu','Älä valitse minne.','Valitse kuinka kauas.','Eurooppa','Aasia','Lähi-itä','Pohjois-Amerikka','Latinalainen Amerikka','Afrikka','Oseania','Valitse vähintään yksi lähtökenttä','Suodattimet muuttuivat — paina Hae','Varaa','Hotellit','Aktiviteetit','Matkan muoto','Mikä tahansa','Pitkä viikonloppu · pe→ma','Viikonloppu · pe→su','Pikamatka · la→su','Löytö','vs. odotettu hinta','alimmassa 10 %:ssa','mediaanin alle'],
pl:['Szukaj','Metoda','Przejrzystość','Udostępnij','Skopiowano','Dzień','Noc','Platforma','Wkrótce','Lotniska wylotu','Kierunki','Zweryfikowane taryfy','Najlepszy stosunek','Wylot','Kontynent','Kraj','Lotnisko','Wszystkie','Wyczyść','wybrane','Cel','Gdziekolwiek','Obróć globus i dotknij kraju','Kiedy','Dni do wylotu','Za ile dni lecisz, licząc od dziś. Możesz wybrać kilka przedziałów.','Maksymalna odległość','Maksymalny budżet','Bagaż rejestrowany','Waluta','Język','Szukaj kraju lub lotniska','Szukaj','Znalezione trasy','Sortuj według','Trasa','Cena','Odległość','Pobyt','Wynik','Sprawdź','nocy','w obie strony','w jedną stronę','Bezpośredni','Kopiuj link','Brak taryf dla tych filtrów','Poszerz zakres dni lub usuń filtr','Gdziekolwiek z','Pokaż wszystkie','Zarejestrowano','Przestań wybierać dokąd.','Wybierz jak daleko.','Europa','Azja','Bliski Wschód','Ameryka Północna','Ameryka Łacińska','Afryka','Oceania','Wybierz co najmniej jedno lotnisko wylotu','Zmieniono filtry — naciśnij Szukaj','Rezerwuj','Hotele','Atrakcje','Kształt podróży','Dowolny','Długi weekend · pt→pon','Weekend · pt→niedz','Krótki wypad · sob→niedz','Okazja','wobec ceny oczekiwanej','w najniższych 10%','poniżej mediany'],
cs:['Hledat','Metoda','Transparentnost','Sdílet','Zkopírováno','Den','Noc','Platforma','Již brzy','Odletová letiště','Destinace','Ověřené ceny','Nejlepší poměr','Odlet','Kontinent','Země','Letiště','Vše','Vymazat','vybráno','Destinace','Kamkoli','Otočte globus a klepněte na zemi','Kdy','Dny do odletu','Za kolik dní letíte, počítáno ode dneška. Můžete vybrat víc pásem.','Maximální vzdálenost','Maximální rozpočet','Odbavené zavazadlo','Měna','Jazyk','Hledat zemi nebo letiště','Hledat','Nalezené trasy','Řadit podle','Trasa','Cena','Vzdálenost','Pobyt','Skóre','Ověřit','nocí','zpáteční','na jednu cestu','Přímý','Kopírovat odkaz','Žádná cena pro tyto filtry','Rozšiřte rozsah dní nebo odeberte filtr','Kamkoli z','Zobrazit vše','Zaznamenáno','Přestaňte vybírat kam.','Vyberte jak daleko.','Evropa','Asie','Blízký východ','Severní Amerika','Latinská Amerika','Afrika','Oceánie','Vyberte alespoň jedno odletové letiště','Filtry změněny — stiskněte Hledat','Rezervovat','Hotely','Zážitky','Tvar cesty','Libovolný','Dlouhý víkend · pá→po','Víkend · pá→ne','Krátký výlet · so→ne','Sleva','vs. očekávaná cena','v nejnižších 10 %','pod mediánem'],
hu:['Keresés','Módszer','Átláthatóság','Megosztás','Másolva','Nappal','Éjszaka','Platform','Hamarosan','Indulási repülőterek','Célállomások','Ellenőrzött árak','Legjobb arány','Indulás','Kontinens','Ország','Repülőtér','Mind','Törlés','kiválasztva','Célállomás','Bárhová','Forgasd a földgömböt, érints egy országot','Mikor','Napok az indulásig','Hány nap múlva utazol, a mai naptól számítva. Több sávot is választhatsz.','Legnagyobb távolság','Legnagyobb keret','Feladott poggyász','Pénznem','Nyelv','Ország vagy repülőtér keresése','Keresés','Talált útvonalak','Rendezés','Útvonal','Ár','Távolság','Tartózkodás','Pontszám','Ellenőrzés','éjszaka','oda-vissza','útirányonként','Közvetlen','Link másolása','Nincs ár ezekkel a szűrőkkel','Bővítsd a napok sávját vagy vegyél le egy szűrőt','Bárhová innen:','Összes mutatása','Rögzítve','Ne azt válaszd, hogy hová.','Válaszd meg, milyen messzire.','Európa','Ázsia','Közel-Kelet','Észak-Amerika','Latin-Amerika','Afrika','Óceánia','Válassz legalább egy indulási repülőteret','A szűrők megváltoztak — nyomd meg a Keresést','Foglalás','Szállás','Programok','Az utazás alakja','Bármelyik','Hosszú hétvége · P→H','Hétvége · P→V','Villámút · Szo→V','Fogás','a várt árhoz képest','a legolcsóbb 10%-ban','a medián alatt'],
ro:['Căutare','Metodă','Transparență','Distribuie','Copiat','Zi','Noapte','Platformă','În curând','Aeroporturi de plecare','Destinații','Tarife verificate','Cel mai bun raport','Plecare','Continent','Țară','Aeroport','Toate','Șterge','selectate','Destinație','Oriunde','Rotește globul și atinge o țară','Când','Zile până la plecare','În câte zile pleci, socotite de azi. Poți alege mai multe intervale.','Distanță maximă','Buget maxim','Bagaj de cală','Monedă','Limbă','Caută o țară sau un aeroport','Caută','Rute găsite','Sortează după','Rută','Preț','Distanță','Sejur','Scor','Verifică','nopți','dus-întors','pe segment','Direct','Copiază linkul','Niciun tarif cu aceste filtre','Lărgește intervalul de zile sau scoate un filtru','Oriunde din','Arată toate','Înregistrat la','Nu mai alege unde.','Alege cât de departe.','Europa','Asia','Orientul Mijlociu','America de Nord','America Latină','Africa','Oceania','Alege cel puțin un aeroport de plecare','Filtre modificate — apasă Caută','Rezervă','Cazare','Activități','Forma călătoriei','Oricare','Weekend prelungit · vin→lun','Weekend · vin→dum','Escapadă · sâm→dum','Chilipir','față de prețul așteptat','în cele mai mici 10%','sub mediană'],
el:['Αναζήτηση','Μέθοδος','Διαφάνεια','Κοινοποίηση','Αντιγράφηκε','Ημέρα','Νύχτα','Πλατφόρμα','Σύντομα','Αεροδρόμια αναχώρησης','Προορισμοί','Επαληθευμένοι ναύλοι','Καλύτερη σχέση','Αναχώρηση','Ήπειρος','Χώρα','Αεροδρόμιο','Όλα','Καθαρισμός','επιλεγμένα','Προορισμός','Οπουδήποτε','Γύρισε την υδρόγειο, άγγιξε μια χώρα','Πότε','Ημέρες ως την αναχώρηση','Σε πόσες ημέρες φεύγεις, από σήμερα. Μπορείς να διαλέξεις πολλά διαστήματα.','Μέγιστη απόσταση','Μέγιστος προϋπολογισμός','Αποσκευή παράδοσης','Νόμισμα','Γλώσσα','Αναζήτηση χώρας ή αεροδρομίου','Αναζήτηση','Διαδρομές που βρέθηκαν','Ταξινόμηση κατά','Διαδρομή','Τιμή','Απόσταση','Διαμονή','Βαθμολογία','Έλεγχος','νύχτες','μετ’ επιστροφής','ανά σκέλος','Απευθείας','Αντιγραφή συνδέσμου','Κανένας ναύλος με αυτά τα φίλτρα','Διεύρυνε το εύρος ημερών ή αφαίρεσε ένα φίλτρο','Οπουδήποτε από','Εμφάνιση όλων','Καταγράφηκε','Μη διαλέγεις πού.','Διάλεξε πόσο μακριά.','Ευρώπη','Ασία','Μέση Ανατολή','Βόρεια Αμερική','Λατινική Αμερική','Αφρική','Ωκεανία','Διάλεξε τουλάχιστον ένα αεροδρόμιο αναχώρησης','Τα φίλτρα άλλαξαν — πάτησε Αναζήτηση','Κράτηση','Ξενοδοχεία','Δραστηριότητες','Μορφή ταξιδιού','Οποιαδήποτε','Τριήμερο · Παρ→Δευ','Σαββατοκύριακο · Παρ→Κυρ','Σύντομο ταξίδι · Σαβ→Κυρ','Ευκαιρία','έναντι αναμενόμενης τιμής','στο χαμηλότερο 10%','κάτω από τη διάμεσο'],
bg:['Търсене','Метод','Прозрачност','Сподели','Копирано','Ден','Нощ','Платформа','Очаквайте','Летища на излитане','Дестинации','Проверени цени','Най-добро съотношение','Излитане','Континент','Държава','Летище','Всички','Изчисти','избрани','Дестинация','Навсякъде','Завърти глобуса и докосни държава','Кога','Дни до излитане','След колко дни летиш, считано от днес. Може да избереш няколко периода.','Максимално разстояние','Максимален бюджет','Чекиран багаж','Валута','Език','Търси държава или летище','Търси','Намерени маршрути','Подреди по','Маршрут','Цена','Разстояние','Престой','Оценка','Провери','нощувки','двупосочно','на отсечка','Директен','Копирай връзката','Няма цена с тези филтри','Разшири периода в дни или махни филтър','Навсякъде от','Покажи всички','Отчетено на','Спри да избираш къде.','Избери колко далеч.','Европа','Азия','Близък изток','Северна Америка','Латинска Америка','Африка','Океания','Избери поне едно летище на излитане','Филтрите са променени — натисни Търси','Резервирай','Хотели','Забавления','Форма на пътуването','Всякаква','Дълъг уикенд · пет→пон','Уикенд · пет→нед','Кратко бягство · съб→нед','Оферта','спрямо очакваната цена','в най-ниските 10%','под медианата'],
sw:['Tafuta','Mbinu','Uwazi','Shiriki','Imenakiliwa','Mchana','Usiku','Jukwaa','Inakuja','Viwanja vya ndege vya kuondokea','Maeneo ya kufika','Nauli zilizothibitishwa','Uwiano bora','Kuondoka','Bara','Nchi','Uwanja wa ndege','Zote','Futa','zimechaguliwa','Unakoenda','Popote','Zungusha dunia, gusa nchi','Lini','Siku hadi kuondoka','Baada ya siku ngapi unasafiri, kuanzia leo. Unaweza kuchagua vipindi kadhaa.','Umbali wa juu','Bajeti ya juu','Mzigo wa kuhifadhiwa','Sarafu','Lugha','Tafuta nchi au uwanja wa ndege','Tafuta','Njia zilizopatikana','Panga kwa','Njia','Bei','Umbali','Kukaa','Alama','Thibitisha','usiku','kwenda na kurudi','kwa safari moja','Moja kwa moja','Nakili kiungo','Hakuna nauli kwa vichujio hivi','Panua kipindi cha siku au ondoa kichujio','Popote kutoka','Onyesha zote','Ilirekodiwa','Acha kuchagua wapi.','Chagua umbali gani.','Ulaya','Asia','Mashariki ya Kati','Amerika Kaskazini','Amerika ya Kilatini','Afrika','Oceania','Chagua angalau uwanja mmoja wa ndege wa kuondokea','Vichujio vimebadilika — bonyeza Tafuta','Weka nafasi','Hoteli','Shughuli','Umbo la safari','Yoyote','Wikendi ndefu · Ijm→Jtt','Wikendi · Ijm→Jpi','Safari fupi · Jmo→Jpi','Punguzo','dhidi ya bei inayotarajiwa','katika 10% ya chini','chini ya wastani'],
tr:['Arama','Yöntem','Şeffaflık','Paylaş','Kopyalandı','Gündüz','Gece','Platform','Yakında','Kalkış havalimanları','Varış noktaları','Doğrulanmış ücretler','En iyi oran','Kalkış','Kıta','Ülke','Havalimanı','Tümü','Temizle','seçili','Varış','Her yere','Küreyi çevir, bir ülkeye dokun','Ne zaman','Kalkışa kalan gün','Bugünden sayarak kaç gün sonra uçuyorsun. Birden çok aralık seçebilirsin.','Azami mesafe','Azami bütçe','Kayıtlı bagaj','Para birimi','Dil','Ülke veya havalimanı ara','Ara','Bulunan rotalar','Sırala','Rota','Fiyat','Mesafe','Konaklama','Puan','Doğrula','gece','gidiş-dönüş','tek yön','Direkt','Bağlantıyı kopyala','Bu filtrelerle ücret yok','Gün aralığını genişlet veya bir filtreyi kaldır','Şuradan her yere:','Tümünü göster','Kayıt tarihi','Nereye sorusunu bırak.','Ne kadar uzağa, onu seç.','Avrupa','Asya','Orta Doğu','Kuzey Amerika','Latin Amerika','Afrika','Okyanusya','En az bir kalkış havalimanı seç','Filtreler değişti — Ara’ya bas','Rezervasyon','Oteller','Aktiviteler','Yolculuk biçimi','Herhangi','Uzun hafta sonu · Cum→Pzt','Hafta sonu · Cum→Paz','Kısa kaçamak · Cmt→Paz','Fırsat','beklenen fiyata göre','en düşük %10 içinde','medyanın altında'],
ru:['Поиск','Метод','Прозрачность','Поделиться','Скопировано','День','Ночь','Платформа','Скоро','Аэропорты вылета','Направления','Проверенные тарифы','Лучшее соотношение','Вылет','Континент','Страна','Аэропорт','Все','Очистить','выбрано','Направление','Куда угодно','Вращайте глобус, коснитесь страны','Когда','Дней до вылета','Через сколько дней вы летите, считая от сегодня. Можно выбрать несколько диапазонов.','Максимальное расстояние','Максимальный бюджет','Багаж','Валюта','Язык','Найти страну или аэропорт','Искать','Найдено маршрутов','Сортировать по','Маршрут','Цена','Расстояние','Пребывание','Оценка','Проверить','ночей','туда и обратно','в одну сторону','Прямой','Копировать ссылку','Нет тарифов с этими фильтрами','Расширьте диапазон дней или снимите фильтр','Куда угодно из','Показать все','Зафиксировано','Перестаньте выбирать куда.','Выберите как далеко.','Европа','Азия','Ближний Восток','Северная Америка','Латинская Америка','Африка','Океания','Выберите хотя бы один аэропорт вылета','Фильтры изменены — нажмите «Искать»','Забронировать','Отели','Экскурсии','Форма поездки','Любая','Длинные выходные · пт→пн','Выходные · пт→вс','Короткая поездка · сб→вс','Выгода','к ожидаемой цене','в нижних 10%','ниже медианы'],
uk:['Пошук','Метод','Прозорість','Поділитися','Скопійовано','День','Ніч','Платформа','Незабаром','Аеропорти вильоту','Напрямки','Перевірені тарифи','Найкраще співвідношення','Виліт','Континент','Країна','Аеропорт','Усі','Очистити','вибрано','Напрямок','Будь-куди','Оберніть глобус, торкніться країни','Коли','Днів до вильоту','Через скільки днів ви летите, рахуючи від сьогодні. Можна обрати кілька діапазонів.','Максимальна відстань','Максимальний бюджет','Багаж','Валюта','Мова','Знайти країну або аеропорт','Шукати','Знайдено маршрутів','Сортувати за','Маршрут','Ціна','Відстань','Перебування','Оцінка','Перевірити','ночей','туди й назад','в один бік','Прямий','Копіювати посилання','Немає тарифів із цими фільтрами','Розширте діапазон днів або зніміть фільтр','Будь-куди з','Показати всі','Зафіксовано','Перестаньте обирати куди.','Оберіть як далеко.','Європа','Азія','Близький Схід','Північна Америка','Латинська Америка','Африка','Океанія','Оберіть хоча б один аеропорт вильоту','Фільтри змінено — натисніть «Шукати»','Забронювати','Готелі','Екскурсії','Форма подорожі','Будь-яка','Довгі вихідні · пт→пн','Вихідні · пт→нд','Коротка поїздка · сб→нд','Вигода','до очікуваної ціни','у нижніх 10%','нижче медіани'],
ar:['بحث','المنهج','الشفافية','مشاركة','تم النسخ','نهار','ليل','المنصة','قريباً','مطارات المغادرة','الوجهات','أسعار موثّقة','أفضل نسبة','المغادرة','القارة','الدولة','المطار','الكل','مسح','محدَّدة','الوجهة','إلى أي مكان','أدر الكرة الأرضية والمس دولة','متى','أيام حتى المغادرة','بعد كم يوم تسافر، محسوبة من اليوم. يمكنك اختيار أكثر من فترة.','أقصى مسافة','أقصى ميزانية','حقيبة مسجّلة','العملة','اللغة','ابحث عن دولة أو مطار','ابحث','المسارات الموجودة','ترتيب حسب','المسار','السعر','المسافة','الإقامة','النقاط','تحقّق','ليالٍ','ذهاب وإياب','لكل اتجاه','مباشر','نسخ الرابط','لا توجد أسعار بهذه الفلاتر','وسّع نطاق الأيام أو أزل فلتراً','إلى أي مكان من','عرض الكل','رُصد في','لا تختر إلى أين.','اختر إلى أي مدى.','أوروبا','آسيا','الشرق الأوسط','أمريكا الشمالية','أمريكا اللاتينية','أفريقيا','أوقيانوسيا','اختر مطار مغادرة واحداً على الأقل','تغيّرت الفلاتر — اضغط ابحث','احجز','فنادق','أنشطة','شكل الرحلة','أي شكل','عطلة طويلة · جمعة→اثنين','عطلة نهاية الأسبوع · جمعة→أحد','رحلة قصيرة · سبت→أحد','الفارق','مقابل السعر المتوقع','ضمن أدنى 10%','دون الوسيط'],
he:['חיפוש','שיטה','שקיפות','שיתוף','הועתק','יום','לילה','פלטפורמה','בקרוב','שדות תעופה ליציאה','יעדים','מחירים מאומתים','היחס הטוב ביותר','יציאה','יבשת','מדינה','שדה תעופה','הכול','ניקוי','נבחרו','יעד','לכל מקום','סובב את הגלובוס וגע במדינה','מתי','ימים עד היציאה','בעוד כמה ימים אתה טס, מהיום. אפשר לבחור כמה טווחים.','מרחק מרבי','תקציב מרבי','מזוודה לבטן המטוס','מטבע','שפה','חפש מדינה או שדה תעופה','חפש','מסלולים שנמצאו','מיין לפי','מסלול','מחיר','מרחק','שהייה','ניקוד','אימות','לילות','הלוך ושוב','לכל כיוון','ישיר','העתק קישור','אין מחיר בפילטרים האלה','הרחב את טווח הימים או הסר פילטר','לכל מקום מ־','הצג הכול','נרשם ב','אל תבחר לאן.','בחר כמה רחוק.','אירופה','אסיה','המזרח התיכון','צפון אמריקה','אמריקה הלטינית','אפריקה','אוקיאניה','בחר לפחות שדה תעופה אחד ליציאה','הפילטרים השתנו — לחץ חפש','הזמנה','מלונות','פעילויות','צורת הנסיעה','הכול','סופ״ש ארוך · ו׳→ב׳','סופ״ש · ו׳→א׳','נסיעה קצרה · ש׳→א׳','מציאה','מול המחיר הצפוי','ב־10% הנמוכים','מתחת לחציון'],
fa:['جستجو','روش','شفافیت','اشتراک‌گذاری','کپی شد','روز','شب','پلتفرم','به‌زودی','فرودگاه‌های مبدأ','مقصدها','نرخ‌های تأییدشده','بهترین نسبت','مبدأ','قاره','کشور','فرودگاه','همه','پاک کردن','انتخاب‌شده','مقصد','هر جا','کره را بچرخانید و کشوری را لمس کنید','چه زمانی','روز تا پرواز','چند روز دیگر پرواز می‌کنید، از امروز. می‌توانید چند بازه را انتخاب کنید.','بیشترین فاصله','بیشترین بودجه','بار تحویلی','ارز','زبان','کشور یا فرودگاه را جستجو کنید','جستجو','مسیرهای یافت‌شده','مرتب‌سازی بر پایهٔ','مسیر','قیمت','فاصله','اقامت','امتیاز','بررسی','شب','رفت و برگشت','یک‌طرفه','مستقیم','کپی کردن پیوند','با این صافی‌ها نرخی نیست','بازهٔ روزها را بازتر کنید یا صافی را بردارید','هر جا از','نمایش همه','ثبت‌شده در','دیگر «کجا» را انتخاب نکنید.','«چقدر دور» را انتخاب کنید.','اروپا','آسیا','خاورمیانه','آمریکای شمالی','آمریکای لاتین','آفریقا','اقیانوسیه','دست‌کم یک فرودگاه مبدأ انتخاب کنید','صافی‌ها تغییر کرد — جستجو را بزنید','رزرو','هتل‌ها','گشت‌ها','شکل سفر','هر کدام','آخر هفتهٔ بلند · جمعه→دوشنبه','آخر هفته · جمعه→یکشنبه','سفر کوتاه · شنبه→یکشنبه','تخفیف','نسبت به قیمت مورد انتظار','در ۱۰٪ پایین','زیر میانه'],
ur:['تلاش','طریقہ','شفافیت','شیئر','نقل ہو گیا','دن','رات','پلیٹ فارم','جلد آ رہا ہے','روانگی کے ہوائی اڈے','منزلیں','تصدیق شدہ کرائے','بہترین تناسب','روانگی','براعظم','ملک','ہوائی اڈہ','سب','صاف کریں','منتخب','منزل','کہیں بھی','کرہ گھمائیں، کسی ملک کو چھوئیں','کب','روانگی میں دن','آج سے گن کر کتنے دن بعد سفر کر رہے ہیں۔ ایک سے زیادہ مدت چن سکتے ہیں۔','زیادہ سے زیادہ فاصلہ','زیادہ سے زیادہ بجٹ','چیک اِن سامان','کرنسی','زبان','ملک یا ہوائی اڈہ تلاش کریں','تلاش کریں','ملنے والے راستے','ترتیب بمطابق','راستہ','قیمت','فاصلہ','قیام','اسکور','تصدیق','راتیں','آمد و رفت','فی طرف','براہِ راست','لنک نقل کریں','ان فلٹرز پر کوئی کرایہ نہیں','دنوں کی حد بڑھائیں یا فلٹر ہٹائیں','کہیں بھی، روانگی','سب دکھائیں','ریکارڈ کیا گیا','یہ مت چنیں کہ کہاں۔','یہ چنیں کہ کتنی دور۔','یورپ','ایشیا','مشرقِ وسطیٰ','شمالی امریکہ','لاطینی امریکہ','افریقہ','اوقیانوسیہ','کم از کم ایک روانگی کا ہوائی اڈہ منتخب کریں','فلٹرز بدل گئے — تلاش دبائیں','بُک کریں','ہوٹل','سرگرمیاں','سفر کی شکل','کوئی بھی','لمبا ویک اینڈ · جمعہ→پیر','ویک اینڈ · جمعہ→اتوار','مختصر سفر · ہفتہ→اتوار','رعایت','متوقع قیمت کے مقابلے','سب سے کم ۱۰٪ میں','وسط سے نیچے'],
hi:['खोज','विधि','पारदर्शिता','साझा करें','कॉपी हुआ','दिन','रात','प्लेटफ़ॉर्म','जल्द आ रहा है','प्रस्थान हवाई अड्डे','गंतव्य','सत्यापित किराए','सर्वोत्तम अनुपात','प्रस्थान','महाद्वीप','देश','हवाई अड्डा','सभी','साफ़ करें','चयनित','गंतव्य','कहीं भी','ग्लोब घुमाएँ, किसी देश को छुएँ','कब','प्रस्थान में दिन','आज से गिनकर कितने दिन बाद उड़ान है। एक से अधिक अवधि चुन सकते हैं।','अधिकतम दूरी','अधिकतम बजट','चेक-इन सामान','मुद्रा','भाषा','देश या हवाई अड्डा खोजें','खोजें','मिले मार्ग','क्रम इसके अनुसार','मार्ग','कीमत','दूरी','ठहराव','अंक','जाँचें','रातें','आना-जाना','प्रति तरफ़','सीधा','लिंक कॉपी करें','इन फ़िल्टरों पर कोई किराया नहीं','दिनों की सीमा बढ़ाएँ या फ़िल्टर हटाएँ','कहीं भी, प्रस्थान','सभी दिखाएँ','दर्ज किया गया','कहाँ चुनना छोड़िए।','कितनी दूर, वह चुनिए।','यूरोप','एशिया','मध्य पूर्व','उत्तर अमेरिका','लैटिन अमेरिका','अफ़्रीका','ओशिनिया','कम से कम एक प्रस्थान हवाई अड्डा चुनें','फ़िल्टर बदले — खोजें दबाएँ','बुक करें','होटल','गतिविधियाँ','यात्रा का आकार','कोई भी','लंबा वीकेंड · शुक्र→सोम','वीकेंड · शुक्र→रवि','छोटी यात्रा · शनि→रवि','छूट','अपेक्षित कीमत से','सबसे कम 10% में','माध्यिका से नीचे'],
bn:['অনুসন্ধান','পদ্ধতি','স্বচ্ছতা','ভাগ করুন','কপি হয়েছে','দিন','রাত','প্ল্যাটফর্ম','শীঘ্রই আসছে','প্রস্থানের বিমানবন্দর','গন্তব্য','যাচাই করা ভাড়া','সেরা অনুপাত','প্রস্থান','মহাদেশ','দেশ','বিমানবন্দর','সব','মুছুন','নির্বাচিত','গন্তব্য','যেকোনো জায়গায়','গ্লোব ঘোরান, একটি দেশ ছুঁন','কখন','প্রস্থানে বাকি দিন','আজ থেকে গুনে কত দিন পরে উড়ছেন। একাধিক সময়সীমা বেছে নিতে পারেন।','সর্বোচ্চ দূরত্ব','সর্বোচ্চ বাজেট','চেক করা ব্যাগ','মুদ্রা','ভাষা','দেশ বা বিমানবন্দর খুঁজুন','খুঁজুন','পাওয়া রুট','সাজান','রুট','দাম','দূরত্ব','অবস্থান','স্কোর','যাচাই','রাত','যাওয়া-আসা','প্রতি পথে','সরাসরি','লিংক কপি করুন','এই ফিল্টারে কোনো ভাড়া নেই','দিনের পরিসর বাড়ান বা ফিল্টার সরান','যেকোনো জায়গায়, প্রস্থান','সব দেখান','রেকর্ড করা','কোথায়, তা বাছা ছাড়ুন।','কত দূর, তা বাছুন।','ইউরোপ','এশিয়া','মধ্যপ্রাচ্য','উত্তর আমেরিকা','লাতিন আমেরিকা','আফ্রিকা','ওশেনিয়া','অন্তত একটি প্রস্থানের বিমানবন্দর বেছে নিন','ফিল্টার বদলেছে — খুঁজুন চাপুন','বুক করুন','হোটেল','অ্যাক্টিভিটি','ভ্রমণের ধরন','যেকোনো','লম্বা সপ্তাহান্ত · শুক্র→সোম','সপ্তাহান্ত · শুক্র→রবি','ছোট ভ্রমণ · শনি→রবি','ছাড়','প্রত্যাশিত দামের তুলনায়','সবচেয়ে কম ১০%-এ','মধ্যমার নিচে'],
ta:['தேடல்','முறை','வெளிப்படைத்தன்மை','பகிர்','நகலெடுக்கப்பட்டது','பகல்','இரவு','தளம்','விரைவில்','புறப்படும் விமான நிலையங்கள்','சேருமிடங்கள்','சரிபார்க்கப்பட்ட கட்டணங்கள்','சிறந்த விகிதம்','புறப்பாடு','கண்டம்','நாடு','விமான நிலையம்','அனைத்தும்','அழி','தேர்ந்தெடுக்கப்பட்டவை','சேருமிடம்','எங்கும்','உலகக் கோளத்தைச் சுழற்றி ஒரு நாட்டைத் தொடுங்கள்','எப்போது','புறப்பாட்டுக்கு நாட்கள்','இன்றிலிருந்து எத்தனை நாட்களில் பயணம். ஒன்றுக்கு மேற்பட்ட வரம்புகளைத் தேர்வு செய்யலாம்.','அதிகபட்ச தூரம்','அதிகபட்ச நிதி','ஒப்படைத்த பயணப்பை','நாணயம்','மொழி','நாடு அல்லது விமான நிலையத்தைத் தேடுங்கள்','தேடு','கிடைத்த வழிகள்','வரிசைப்படுத்து','வழி','விலை','தூரம்','தங்கல்','மதிப்பெண்','சரிபார்','இரவுகள்','இருவழி','ஒருவழி','நேரடி','இணைப்பை நகலெடு','இந்த வடிகட்டிகளுக்குக் கட்டணம் இல்லை','நாட்கள் வரம்பை விரிவாக்குங்கள் அல்லது வடிகட்டியை நீக்குங்கள்','எங்கும், புறப்பாடு','அனைத்தையும் காட்டு','பதிவு செய்யப்பட்டது','எங்கே என்பதைத் தேர்வதை விடுங்கள்.','எவ்வளவு தூரம் என்பதைத் தேர்ந்தெடுங்கள்.','ஐரோப்பா','ஆசியா','மத்திய கிழக்கு','வட அமெரிக்கா','லத்தீன் அமெரிக்கா','ஆப்பிரிக்கா','ஓசியானியா','குறைந்தது ஒரு புறப்பாட்டு விமான நிலையத்தைத் தேர்ந்தெடுங்கள்','வடிகட்டிகள் மாறின — தேடு அழுத்துங்கள்','முன்பதிவு','ஹோட்டல்கள்','அனுபவங்கள்','பயணத்தின் வடிவம்','எதுவும்','நீண்ட வார இறுதி · வெள்→திங்','வார இறுதி · வெள்→ஞாயி','குறு பயணம் · சனி→ஞாயி','சலுகை','எதிர்பார்த்த விலையுடன்','குறைந்த 10%-இல்','இடைநிலைக்குக் கீழ்'],
id:['Pencarian','Metode','Transparansi','Bagikan','Tersalin','Siang','Malam','Platform','Segera hadir','Bandara keberangkatan','Tujuan','Tarif terverifikasi','Rasio terbaik','Keberangkatan','Benua','Negara','Bandara','Semua','Hapus','dipilih','Tujuan','Ke mana saja','Putar bola dunia, sentuh sebuah negara','Kapan','Hari menuju keberangkatan','Berapa hari lagi Anda terbang, dihitung dari hari ini. Bisa pilih lebih dari satu rentang.','Jarak maksimum','Anggaran maksimum','Bagasi tercatat','Mata uang','Bahasa','Cari negara atau bandara','Cari','Rute ditemukan','Urutkan menurut','Rute','Harga','Jarak','Menginap','Skor','Verifikasi','malam','pulang pergi','sekali jalan','Langsung','Salin tautan','Tidak ada tarif dengan filter ini','Perluas rentang hari atau hapus satu filter','Ke mana saja dari','Tampilkan semua','Dicatat pada','Berhenti memilih ke mana.','Pilih seberapa jauh.','Eropa','Asia','Timur Tengah','Amerika Utara','Amerika Latin','Afrika','Oseania','Pilih minimal satu bandara keberangkatan','Filter berubah — tekan Cari','Pesan','Hotel','Aktivitas','Bentuk perjalanan','Apa saja','Akhir pekan panjang · Jum→Sen','Akhir pekan · Jum→Min','Perjalanan singkat · Sab→Min','Selisih','vs harga perkiraan','di 10% terendah','di bawah median'],
ms:['Carian','Kaedah','Ketelusan','Kongsi','Disalin','Siang','Malam','Platform','Akan datang','Lapangan terbang berlepas','Destinasi','Tambang disahkan','Nisbah terbaik','Berlepas','Benua','Negara','Lapangan terbang','Semua','Kosongkan','dipilih','Destinasi','Ke mana sahaja','Putar glob, sentuh sebuah negara','Bila','Hari hingga berlepas','Berapa hari lagi anda terbang, dikira dari hari ini. Boleh pilih lebih daripada satu julat.','Jarak maksimum','Belanjawan maksimum','Bagasi berdaftar','Mata wang','Bahasa','Cari negara atau lapangan terbang','Cari','Laluan dijumpai','Susun mengikut','Laluan','Harga','Jarak','Penginapan','Skor','Sahkan','malam','pergi balik','sehala','Terus','Salin pautan','Tiada tambang dengan penapis ini','Luaskan julat hari atau buang penapis','Ke mana sahaja dari','Tunjuk semua','Direkod pada','Berhenti memilih ke mana.','Pilih sejauh mana.','Eropah','Asia','Timur Tengah','Amerika Utara','Amerika Latin','Afrika','Oceania','Pilih sekurang-kurangnya satu lapangan terbang berlepas','Penapis berubah — tekan Cari','Tempah','Hotel','Aktiviti','Bentuk perjalanan','Apa-apa','Hujung minggu panjang · Jum→Isn','Hujung minggu · Jum→Ahd','Perjalanan singkat · Sab→Ahd','Jimat','berbanding harga jangkaan','dalam 10% terendah','di bawah median'],
tl:['Paghahanap','Paraan','Transparensya','Ibahagi','Nakopya','Araw','Gabi','Plataporma','Paparating','Mga paliparan ng alis','Mga destinasyon','Beripikadong pasahe','Pinakamahusay na ratio','Pag-alis','Kontinente','Bansa','Paliparan','Lahat','Burahin','napili','Destinasyon','Kahit saan','Iikot ang globo, pindutin ang bansa','Kailan','Araw bago umalis','Ilang araw mula ngayon bago ka lumipad. Puwedeng pumili ng higit sa isa.','Pinakamalayong distansya','Pinakamataas na budget','Check-in na bagahe','Salapi','Wika','Maghanap ng bansa o paliparan','Maghanap','Mga rutang natagpuan','Ayusin ayon sa','Ruta','Presyo','Distansya','Pananatili','Iskor','Suriin','gabi','balikan','bawat biyahe','Diretso','Kopyahin ang link','Walang pasaheng tumutugma','Palawakin ang saklaw ng araw o mag-alis ng filter','Kahit saan mula sa','Ipakita lahat','Naitala noong','Huwag nang piliin kung saan.','Piliin kung gaano kalayo.','Europa','Asya','Gitnang Silangan','Hilagang Amerika','Latin Amerika','Aprika','Oceania','Pumili ng kahit isang paliparan ng alis','Nabago ang mga filter — pindutin ang Maghanap','Mag-book','Mga hotel','Mga aktibidad','Hugis ng biyahe','Kahit alin','Mahabang weekend · Biy→Lun','Weekend · Biy→Lin','Maikling biyahe · Sab→Lin','Tipid','kumpara sa inaasahang presyo','nasa pinakamababang 10%','sa ilalim ng median'],
vi:['Tìm kiếm','Phương pháp','Minh bạch','Chia sẻ','Đã sao chép','Ngày','Đêm','Nền tảng','Sắp có','Sân bay khởi hành','Điểm đến','Giá vé đã xác minh','Tỉ lệ tốt nhất','Khởi hành','Châu lục','Quốc gia','Sân bay','Tất cả','Xóa','đã chọn','Điểm đến','Bất cứ đâu','Xoay quả cầu, chạm vào một quốc gia','Khi nào','Số ngày đến khi bay','Còn bao nhiêu ngày nữa bạn bay, tính từ hôm nay. Có thể chọn nhiều khoảng.','Khoảng cách tối đa','Ngân sách tối đa','Hành lý ký gửi','Tiền tệ','Ngôn ngữ','Tìm quốc gia hoặc sân bay','Tìm','Tuyến tìm được','Sắp xếp theo','Tuyến','Giá','Khoảng cách','Lưu trú','Điểm','Kiểm tra','đêm','khứ hồi','mỗi chiều','Bay thẳng','Sao chép liên kết','Không có giá vé với bộ lọc này','Mở rộng khoảng ngày hoặc bỏ một bộ lọc','Bất cứ đâu từ','Hiện tất cả','Ghi nhận ngày','Đừng chọn đi đâu nữa.','Hãy chọn đi xa bao nhiêu.','Châu Âu','Châu Á','Trung Đông','Bắc Mỹ','Mỹ Latinh','Châu Phi','Châu Đại Dương','Chọn ít nhất một sân bay khởi hành','Bộ lọc đã đổi — bấm Tìm','Đặt vé','Khách sạn','Hoạt động','Dạng chuyến đi','Bất kỳ','Cuối tuần dài · T6→T2','Cuối tuần · T6→CN','Chuyến ngắn · T7→CN','Chênh lệch','so với giá dự kiến','trong 10% thấp nhất','dưới trung vị'],
th:['ค้นหา','วิธีการ','ความโปร่งใส','แชร์','คัดลอกแล้ว','กลางวัน','กลางคืน','แพลตฟอร์ม','เร็ว ๆ นี้','สนามบินต้นทาง','จุดหมาย','ค่าโดยสารที่ตรวจสอบแล้ว','อัตราส่วนดีที่สุด','ออกเดินทาง','ทวีป','ประเทศ','สนามบิน','ทั้งหมด','ล้าง','ที่เลือก','จุดหมาย','ที่ไหนก็ได้','หมุนลูกโลกแล้วแตะประเทศ','เมื่อไร','จำนวนวันก่อนบิน','อีกกี่วันคุณจะบิน นับจากวันนี้ เลือกได้มากกว่าหนึ่งช่วง','ระยะทางสูงสุด','งบประมาณสูงสุด','สัมภาระใต้ท้องเครื่อง','สกุลเงิน','ภาษา','ค้นหาประเทศหรือสนามบิน','ค้นหา','เส้นทางที่พบ','เรียงตาม','เส้นทาง','ราคา','ระยะทาง','การพัก','คะแนน','ตรวจสอบ','คืน','ไป-กลับ','ต่อเที่ยว','บินตรง','คัดลอกลิงก์','ไม่มีค่าโดยสารตามตัวกรองนี้','ขยายช่วงวันหรือเอาตัวกรองออก','ที่ไหนก็ได้จาก','แสดงทั้งหมด','บันทึกเมื่อ','เลิกเลือกว่าจะไปที่ไหน','เลือกว่าจะไปไกลแค่ไหน','ยุโรป','เอเชีย','ตะวันออกกลาง','อเมริกาเหนือ','ละตินอเมริกา','แอฟริกา','โอเชียเนีย','เลือกสนามบินต้นทางอย่างน้อยหนึ่งแห่ง','ตัวกรองเปลี่ยนแล้ว — กดค้นหา','จอง','โรงแรม','กิจกรรม','รูปแบบการเดินทาง','ทั้งหมด','หยุดยาว · ศุกร์→จันทร์','สุดสัปดาห์ · ศุกร์→อาทิตย์','เที่ยวสั้น · เสาร์→อาทิตย์','ส่วนลด','เทียบราคาที่คาด','ต่ำสุด 10%','ต่ำกว่าค่ามัธยฐาน'],
zh:['搜索','方法','透明度','分享','已复制','日间','夜间','平台','即将推出','出发机场','目的地','已核实票价','最佳性价比','出发','大洲','国家','机场','全部','清除','已选','目的地','任意地点','转动地球，点击国家','时间','距出发天数','从今天算起还有多少天起飞，可多选。','最大距离','最高预算','托运行李','货币','语言','搜索国家或机场','搜索','找到的航线','排序方式','航线','价格','距离','停留','评分','核实','晚','往返','单程','直飞','复制链接','该筛选条件下没有票价','放宽天数范围或去掉一个筛选','任意地点，出发自','显示全部','记录于','别再选去哪里。','选择要走多远。','欧洲','亚洲','中东','北美洲','拉丁美洲','非洲','大洋洲','至少选择一个出发机场','筛选条件已更改 — 请点击搜索','预订','酒店','玩乐','行程形态','不限','长周末 · 周五→周一','周末 · 周五→周日','短途 · 周六→周日','折让','对比预期价','最低 10%','低于中位数'],
ja:['検索','方法','透明性','共有','コピーしました','昼','夜','プラットフォーム','近日公開','出発空港','目的地','検証済み運賃','最良の比率','出発','大陸','国','空港','すべて','クリア','選択済み','目的地','どこへでも','地球儀を回して国をタップ','いつ','出発までの日数','今日から数えて何日後に出発するか。複数選べます。','最大距離','最大予算','受託手荷物','通貨','言語','国または空港を検索','検索','見つかった路線','並べ替え','路線','価格','距離','滞在','スコア','確認','泊','往復','片道あたり','直行','リンクをコピー','この条件に合う運賃はありません','日数の範囲を広げるかフィルターを外してください','どこへでも：','すべて表示','取得日','どこへ行くかを選ぶのはやめよう。','どこまで行くかを選ぼう。','ヨーロッパ','アジア','中東','北アメリカ','ラテンアメリカ','アフリカ','オセアニア','出発空港を少なくとも一つ選んでください','条件が変わりました — 検索を押してください','予約','ホテル','アクティビティ','旅行の形','指定なし','連休 · 金→月','週末 · 金→日','弾丸旅行 · 土→日','割安度','予想価格比','最安10%','中央値以下'],
ko:['검색','방법','투명성','공유','복사됨','주간','야간','플랫폼','출시 예정','출발 공항','목적지','검증된 운임','최고 비율','출발','대륙','국가','공항','전체','지우기','선택됨','목적지','어디든지','지구본을 돌려 국가를 누르세요','언제','출발까지 남은 날','오늘부터 며칠 뒤에 떠나는지. 여러 구간을 고를 수 있습니다.','최대 거리','최대 예산','위탁 수하물','통화','언어','국가 또는 공항 검색','검색','찾은 노선','정렬 기준','노선','가격','거리','체류','점수','확인','박','왕복','편도당','직항','링크 복사','이 필터에 맞는 운임이 없습니다','날짜 범위를 넓히거나 필터를 해제하세요','어디든지:','전체 보기','기록일','어디로 갈지 고르지 마세요.','얼마나 멀리 갈지 고르세요.','유럽','아시아','중동','북아메리카','라틴 아메리카','아프리카','오세아니아','출발 공항을 하나 이상 선택하세요','조건이 바뀌었습니다 — 검색을 누르세요','예약','호텔','액티비티','여행 형태','전체','긴 주말 · 금→월','주말 · 금→일','짧은 여행 · 토→일','할인폭','예상가 대비','최저 10%','중앙값 이하'],
};

/* lingue offerte, con il nome nella lingua stessa (endonimo) e il verso */
const LANG_META = [
 ['en','English'],['zh','中文'],['hi','हिन्दी'],['es','Español'],['ar','العربية',1],['fr','Français'],
 ['bn','বাংলা'],['pt','Português'],['ru','Русский'],['ur','اردو',1],['id','Bahasa Indonesia'],
 ['de','Deutsch'],['ja','日本語'],['tr','Türkçe'],['ko','한국어'],['vi','Tiếng Việt'],['it','Italiano'],
 ['fa','فارسی',1],['th','ไทย'],['pl','Polski'],['nl','Nederlands'],['uk','Українська'],['ro','Română'],
 ['el','Ελληνικά'],['cs','Čeština'],['sv','Svenska'],['hu','Magyar'],['he','עברית',1],
 ['ms','Bahasa Melayu'],['ta','தமிழ்'],['sw','Kiswahili'],['da','Dansk'],['no','Norsk'],['fi','Suomi'],
 ['bg','Български'],['tl','Filipino'],
];

/* ── valute ───────────────────────────────────────────────────────────
   [codice, simbolo, decimali, unita' per 1 EUR].
   I cambi sono una fotografia datata: servono a rendere leggibile un
   prezzo, non a fare cassa. Il prezzo su cui si prenota resta quello
   dell'operatore. Quando la modalita' live e' attiva i prezzi arrivano
   gia' convertiti dalla fonte e questa tabella non viene usata.        */
const FX_DATE = '2026-09-02';
const CUR = [
 ['EUR','€',0,1],            ['USD','$',0,1.1594],       ['GBP','£',0,0.8572],
 ['CHF','CHF',0,0.9408],     ['JPY','¥',0,185.64],       ['CNY','¥',0,7.8063],
 ['AUD','A$',0,1.6219],      ['CAD','C$',0,1.6104],      ['SGD','S$',0,1.4761],
 ['HKD','HK$',0,9.0902],     ['KRW','₩',0,1593.05],      ['INR','₹',0,110.09],
 ['AED','AED',0,4.2579],     ['SAR','SAR',0,4.3478],     ['QAR','QAR',0,4.2202],
 ['KWD','KWD',2,0.3581],     ['BHD','BHD',2,0.4359],     ['OMR','OMR',2,0.4458],
 ['JOD','JOD',2,0.8220],     ['ILS','₪',0,3.5090],       ['TRY','₺',0,55.978],
 ['EGP','EGP',0,58.959],     ['MAD','MAD',0,10.809],     ['TND','TND',2,3.3786],
 ['ZAR','R',0,18.731],       ['NGN','₦',0,1567.19],      ['KES','KSh',0,150.15],
 ['ETB','ETB',0,189.72],     ['MUR','MUR',0,54.569],     ['THB','฿',0,38.570],
 ['VND','₫',0,30036.9],      ['IDR','Rp',0,20582.0],     ['MYR','RM',0,4.6823],
 ['PHP','₱',0,72.341],       ['TWD','NT$',0,36.743],     ['PKR','Rs',0,322.15],
 ['BDT','৳',0,142.26],       ['KZT','₸',0,531.00],       ['AZN','₼',0,1.9710],
 ['GEL','₾',0,3.0368],       ['AMD','֏',0,422.34],       ['UAH','₴',0,51.525],
 ['RSD','RSD',0,117.33],     ['BGN','лв',0,1.9558],      ['RON','lei',0,5.2568],
 ['PLN','zł',0,4.3328],      ['CZK','Kč',0,24.179],      ['HUF','Ft',0,367.27],
 ['SEK','kr',0,11.141],      ['NOK','kr',0,10.815],      ['DKK','kr',0,7.4746],
 ['ISK','kr',0,140.71],      ['BRL','R$',0,6.0007],      ['MXN','MX$',0,19.697],
 ['ARS','ARS',0,1753.87],    ['CLP','CLP',0,1083.55],    ['COP','COP',0,3725.45],
 ['PEN','S/',0,3.8996],      ['NZD','NZ$',0,1.9666],
];
