/* EFFICIENCY LIFE — FLIGHT · lingue e valute
   ------------------------------------------------------------------
   L'interfaccia (etichette, pulsanti, intestazioni) e' tradotta in 36
   lingue: coprono circa cinque miliardi e mezzo di parlanti e tutti i
   mercati di partenza serviti dall'indice. I testi lunghi del capitolo
   "Metodo" e "Trasparenza" restano in italiano e inglese, con l'inglese
   come ripiego: meglio un paragrafo in inglese che una traduzione
   automatica di cui nessuno risponde.
   I nomi di paesi, lingue e valute non sono in queste tabelle: li
   fornisce Intl.DisplayNames del browser, nella lingua scelta.        */

/* ordine delle chiavi: ogni lingua e' un array parallelo a questo */
const KEYS = ['nav_search','nav_method','nav_priv','share','copied','day','night','platform','soon',
 'st_air','st_dest','st_fare','st_best','f_from','f_continent','f_country','f_airport','f_all','f_clear',
 'f_selected','f_to','f_anywhere','f_globe','f_when','f_window','f_dist','f_budget','f_bag','f_currency',
 'f_language','f_searchph','btn_search','b_found','b_sort','th_route','th_price','th_dist','th_stay',
 'th_score','th_check','nights','rt','eachway','direct','copylink','empty_t','empty_b','everywhere',
 'more','obs','h1a','h1b',
 'r_eu','r_as','r_me','r_na','r_la','r_af','r_oc',
 'f_need','f_dirty','book','stay','act'];

const LANGS = {
en:['Search','Method','Transparency','Share','Copied','Day','Night','Platform','Coming soon','Departure airports','Destinations','Verified fares','Best ratio','Departure','Continent','Country','Airport','All','Clear','selected','Destination','Anywhere','Spin the globe, tap a country','When','Departure window (days)','Maximum distance','Maximum budget','Checked bag','Currency','Language','Search a country or airport','Search','Routes found','Sort by','Route','Price','Distance','Stay','Score','Verify','nights','return','each way','Direct','Copy link','No fare matches these filters','Widen the window or drop a filter','Anywhere from','Show all','Observed','Stop choosing where.','Choose how far.','Europe','Asia','Middle East','North America','Latin America','Africa','Oceania','Pick at least one departure airport','Filters changed — press Search','Book','Hotels','Things to do'],
it:['Ricerca','Metodo','Trasparenza','Condividi','Copiato','Giorno','Notte','Piattaforma','In arrivo','Aeroporti di partenza','Destinazioni','Tariffe verificate','Miglior rapporto','Partenza','Continente','Paese','Aeroporto','Tutti','Azzera','selezionati','Destinazione','Ovunque','Ruota il globo, tocca un paese','Quando','Finestra di partenza (giorni)','Distanza massima','Budget massimo','Bagaglio in stiva','Valuta','Lingua','Cerca un paese o un aeroporto','Cerca','Rotte trovate','Ordina per','Rotta','Prezzo','Distanza','Soggiorno','Punteggio','Verifica','notti','andata e ritorno','a tratta','Diretto','Copia link','Nessuna tariffa con questi filtri','Allarga la finestra o togli un filtro','Ovunque da','Mostra tutte','Rilevate il','Non scegliere dove.','Scegli quanto lontano.','Europa','Asia','Medio Oriente','Nord America','America Latina','Africa','Oceania','Scegli almeno un aeroporto di partenza','Filtri cambiati — premi Cerca','Prenota','Hotel','Attività'],
es:['Búsqueda','Método','Transparencia','Compartir','Copiado','Día','Noche','Plataforma','Próximamente','Aeropuertos de salida','Destinos','Tarifas verificadas','Mejor relación','Salida','Continente','País','Aeropuerto','Todos','Borrar','seleccionados','Destino','A cualquier parte','Gira el globo y toca un país','Cuándo','Ventana de salida (días)','Distancia máxima','Presupuesto máximo','Equipaje facturado','Moneda','Idioma','Busca un país o aeropuerto','Buscar','Rutas encontradas','Ordenar por','Ruta','Precio','Distancia','Estancia','Puntuación','Verificar','noches','ida y vuelta','por trayecto','Directo','Copiar enlace','Ninguna tarifa con estos filtros','Amplía la ventana o quita un filtro','A cualquier parte desde','Ver todas','Observado el','Deja de elegir adónde.','Elige cuán lejos.','Europa','Asia','Oriente Medio','América del Norte','América Latina','África','Oceanía','Elige al menos un aeropuerto de salida','Filtros cambiados: pulsa Buscar','Reservar','Hoteles','Actividades'],
fr:['Recherche','Méthode','Transparence','Partager','Copié','Jour','Nuit','Plateforme','Bientôt','Aéroports de départ','Destinations','Tarifs vérifiés','Meilleur rapport','Départ','Continent','Pays','Aéroport','Tous','Effacer','sélectionnés','Destination','Partout','Faites tourner le globe, touchez un pays','Quand','Fenêtre de départ (jours)','Distance maximale','Budget maximal','Bagage en soute','Devise','Langue','Chercher un pays ou un aéroport','Rechercher','Itinéraires trouvés','Trier par','Itinéraire','Prix','Distance','Séjour','Score','Vérifier','nuits','aller-retour','par trajet','Direct','Copier le lien','Aucun tarif avec ces filtres','Élargissez la fenêtre ou retirez un filtre','Partout au départ de','Tout afficher','Relevé le','Ne choisissez plus où.','Choisissez jusqu’où.','Europe','Asie','Moyen-Orient','Amérique du Nord','Amérique latine','Afrique','Océanie','Choisissez au moins un aéroport de départ','Filtres modifiés — appuyez sur Rechercher','Réserver','Hôtels','Activités'],
de:['Suche','Methode','Transparenz','Teilen','Kopiert','Tag','Nacht','Plattform','Demnächst','Abflughäfen','Ziele','Geprüfte Tarife','Bestes Verhältnis','Abflug','Kontinent','Land','Flughafen','Alle','Zurücksetzen','ausgewählt','Ziel','Überallhin','Globus drehen, Land antippen','Wann','Abflugfenster (Tage)','Maximale Entfernung','Maximales Budget','Aufgabegepäck','Währung','Sprache','Land oder Flughafen suchen','Suchen','Gefundene Strecken','Sortieren nach','Strecke','Preis','Entfernung','Aufenthalt','Punktzahl','Prüfen','Nächte','Hin und zurück','pro Strecke','Direkt','Link kopieren','Kein Tarif passt zu diesen Filtern','Fenster erweitern oder Filter entfernen','Überallhin ab','Alle anzeigen','Erfasst am','Hören Sie auf, das Wohin zu wählen.','Wählen Sie das Wie weit.','Europa','Asien','Naher Osten','Nordamerika','Lateinamerika','Afrika','Ozeanien','Wählen Sie mindestens einen Abflughafen','Filter geändert — auf Suchen drücken','Buchen','Hotels','Aktivitäten'],
pt:['Pesquisa','Método','Transparência','Partilhar','Copiado','Dia','Noite','Plataforma','Em breve','Aeroportos de partida','Destinos','Tarifas verificadas','Melhor relação','Partida','Continente','País','Aeroporto','Todos','Limpar','selecionados','Destino','Para qualquer lugar','Gire o globo e toque num país','Quando','Janela de partida (dias)','Distância máxima','Orçamento máximo','Bagagem de porão','Moeda','Idioma','Procurar país ou aeroporto','Pesquisar','Rotas encontradas','Ordenar por','Rota','Preço','Distância','Estadia','Pontuação','Verificar','noites','ida e volta','por trecho','Direto','Copiar ligação','Nenhuma tarifa com estes filtros','Alargue a janela ou retire um filtro','Para qualquer lugar a partir de','Mostrar todas','Observado em','Pare de escolher para onde.','Escolha quão longe.','Europa','Ásia','Médio Oriente','América do Norte','América Latina','África','Oceania','Escolha pelo menos um aeroporto de partida','Filtros alterados — prima Pesquisar','Reservar','Hotéis','Atividades'],
nl:['Zoeken','Methode','Transparantie','Delen','Gekopieerd','Dag','Nacht','Platform','Binnenkort','Vertrekluchthavens','Bestemmingen','Geverifieerde tarieven','Beste verhouding','Vertrek','Continent','Land','Luchthaven','Alle','Wissen','geselecteerd','Bestemming','Overal heen','Draai de globe, tik op een land','Wanneer','Vertrekvenster (dagen)','Maximale afstand','Maximaal budget','Ruimbagage','Valuta','Taal','Zoek een land of luchthaven','Zoeken','Gevonden routes','Sorteren op','Route','Prijs','Afstand','Verblijf','Score','Controleren','nachten','retour','per traject','Direct','Link kopiëren','Geen tarief met deze filters','Verruim het venster of verwijder een filter','Overal heen vanaf','Alles tonen','Waargenomen op','Kies niet langer waarheen.','Kies hoe ver.','Europa','Azië','Midden-Oosten','Noord-Amerika','Latijns-Amerika','Afrika','Oceanië','Kies minstens één vertrekluchthaven','Filters gewijzigd — druk op Zoeken','Boeken','Hotels','Activiteiten'],
sv:['Sök','Metod','Öppenhet','Dela','Kopierad','Dag','Natt','Plattform','Kommer snart','Avreseflygplatser','Destinationer','Verifierade priser','Bästa förhållandet','Avresa','Kontinent','Land','Flygplats','Alla','Rensa','valda','Destination','Vart som helst','Snurra jordgloben, tryck på ett land','När','Avresefönster (dagar)','Största avstånd','Högsta budget','Incheckat bagage','Valuta','Språk','Sök land eller flygplats','Sök','Hittade rutter','Sortera efter','Rutt','Pris','Avstånd','Vistelse','Poäng','Kontrollera','nätter','tur och retur','per sträcka','Direkt','Kopiera länk','Inget pris matchar filtren','Vidga fönstret eller ta bort ett filter','Vart som helst från','Visa alla','Noterat den','Sluta välja vart.','Välj hur långt.','Europa','Asien','Mellanöstern','Nordamerika','Latinamerika','Afrika','Oceanien','Välj minst en avreseflygplats','Filtren ändrade — tryck på Sök','Boka','Hotell','Aktiviteter'],
da:['Søg','Metode','Gennemsigtighed','Del','Kopieret','Dag','Nat','Platform','Kommer snart','Afgangslufthavne','Destinationer','Bekræftede priser','Bedste forhold','Afgang','Kontinent','Land','Lufthavn','Alle','Ryd','valgte','Destination','Overalt','Drej kloden, tryk på et land','Hvornår','Afgangsvindue (dage)','Maksimal afstand','Maksimalt budget','Indchecket bagage','Valuta','Sprog','Søg land eller lufthavn','Søg','Fundne ruter','Sortér efter','Rute','Pris','Afstand','Ophold','Score','Kontrollér','nætter','tur/retur','pr. strækning','Direkte','Kopiér link','Ingen pris med disse filtre','Udvid vinduet eller fjern et filter','Overalt fra','Vis alle','Registreret den','Hold op med at vælge hvorhen.','Vælg hvor langt.','Europa','Asien','Mellemøsten','Nordamerika','Latinamerika','Afrika','Oceanien','Vælg mindst én afgangslufthavn','Filtre ændret — tryk på Søg','Book','Hoteller','Oplevelser'],
no:['Søk','Metode','Åpenhet','Del','Kopiert','Dag','Natt','Plattform','Kommer snart','Avreiseflyplasser','Destinasjoner','Bekreftede priser','Beste forhold','Avreise','Kontinent','Land','Flyplass','Alle','Tøm','valgte','Destinasjon','Overalt','Snurr kloden, trykk på et land','Når','Avreisevindu (dager)','Største avstand','Høyeste budsjett','Innsjekket bagasje','Valuta','Språk','Søk land eller flyplass','Søk','Ruter funnet','Sorter etter','Rute','Pris','Avstand','Opphold','Poeng','Sjekk','netter','tur-retur','per strekning','Direkte','Kopier lenke','Ingen pris med disse filtrene','Utvid vinduet eller fjern et filter','Overalt fra','Vis alle','Registrert','Slutt å velge hvor.','Velg hvor langt.','Europa','Asia','Midtøsten','Nord-Amerika','Latin-Amerika','Afrika','Oseania','Velg minst én avreiseflyplass','Filtrene er endret — trykk Søk','Bestill','Hoteller','Aktiviteter'],
fi:['Haku','Menetelmä','Läpinäkyvyys','Jaa','Kopioitu','Päivä','Yö','Alusta','Tulossa','Lähtökentät','Kohteet','Vahvistetut hinnat','Paras suhde','Lähtö','Manner','Maa','Lentoasema','Kaikki','Tyhjennä','valittu','Kohde','Minne tahansa','Pyöritä palloa, napauta maata','Milloin','Lähtöikkuna (päivää)','Enimmäisetäisyys','Enimmäisbudjetti','Ruumaan menevä laukku','Valuutta','Kieli','Hae maata tai lentoasemaa','Hae','Löytyneet reitit','Järjestä','Reitti','Hinta','Etäisyys','Oleskelu','Pisteet','Tarkista','yötä','meno-paluu','yhteen suuntaan','Suora','Kopioi linkki','Ei hintoja näillä suodattimilla','Laajenna ikkunaa tai poista suodatin','Minne tahansa lähtien','Näytä kaikki','Havaittu','Älä valitse minne.','Valitse kuinka kauas.','Eurooppa','Aasia','Lähi-itä','Pohjois-Amerikka','Latinalainen Amerikka','Afrikka','Oseania','Valitse vähintään yksi lähtökenttä','Suodattimet muuttuivat — paina Hae','Varaa','Hotellit','Aktiviteetit'],
pl:['Szukaj','Metoda','Przejrzystość','Udostępnij','Skopiowano','Dzień','Noc','Platforma','Wkrótce','Lotniska wylotu','Kierunki','Zweryfikowane taryfy','Najlepszy stosunek','Wylot','Kontynent','Kraj','Lotnisko','Wszystkie','Wyczyść','wybrane','Cel','Gdziekolwiek','Obróć globus i dotknij kraju','Kiedy','Okno wylotu (dni)','Maksymalna odległość','Maksymalny budżet','Bagaż rejestrowany','Waluta','Język','Szukaj kraju lub lotniska','Szukaj','Znalezione trasy','Sortuj według','Trasa','Cena','Odległość','Pobyt','Wynik','Sprawdź','nocy','w obie strony','w jedną stronę','Bezpośredni','Kopiuj link','Brak taryf dla tych filtrów','Poszerz okno lub usuń filtr','Gdziekolwiek z','Pokaż wszystkie','Zarejestrowano','Przestań wybierać dokąd.','Wybierz jak daleko.','Europa','Azja','Bliski Wschód','Ameryka Północna','Ameryka Łacińska','Afryka','Oceania','Wybierz co najmniej jedno lotnisko wylotu','Zmieniono filtry — naciśnij Szukaj','Rezerwuj','Hotele','Atrakcje'],
cs:['Hledat','Metoda','Transparentnost','Sdílet','Zkopírováno','Den','Noc','Platforma','Již brzy','Odletová letiště','Destinace','Ověřené ceny','Nejlepší poměr','Odlet','Kontinent','Země','Letiště','Vše','Vymazat','vybráno','Destinace','Kamkoli','Otočte globus a klepněte na zemi','Kdy','Okno odletu (dny)','Maximální vzdálenost','Maximální rozpočet','Odbavené zavazadlo','Měna','Jazyk','Hledat zemi nebo letiště','Hledat','Nalezené trasy','Řadit podle','Trasa','Cena','Vzdálenost','Pobyt','Skóre','Ověřit','nocí','zpáteční','na jednu cestu','Přímý','Kopírovat odkaz','Žádná cena pro tyto filtry','Rozšiřte okno nebo odeberte filtr','Kamkoli z','Zobrazit vše','Zaznamenáno','Přestaňte vybírat kam.','Vyberte jak daleko.','Evropa','Asie','Blízký východ','Severní Amerika','Latinská Amerika','Afrika','Oceánie','Vyberte alespoň jedno odletové letiště','Filtry změněny — stiskněte Hledat','Rezervovat','Hotely','Zážitky'],
hu:['Keresés','Módszer','Átláthatóság','Megosztás','Másolva','Nappal','Éjszaka','Platform','Hamarosan','Indulási repülőterek','Célállomások','Ellenőrzött árak','Legjobb arány','Indulás','Kontinens','Ország','Repülőtér','Mind','Törlés','kiválasztva','Célállomás','Bárhová','Forgasd a földgömböt, érints egy országot','Mikor','Indulási ablak (nap)','Legnagyobb távolság','Legnagyobb keret','Feladott poggyász','Pénznem','Nyelv','Ország vagy repülőtér keresése','Keresés','Talált útvonalak','Rendezés','Útvonal','Ár','Távolság','Tartózkodás','Pontszám','Ellenőrzés','éjszaka','oda-vissza','útirányonként','Közvetlen','Link másolása','Nincs ár ezekkel a szűrőkkel','Bővítsd az ablakot vagy vegyél le egy szűrőt','Bárhová innen:','Összes mutatása','Rögzítve','Ne azt válaszd, hogy hová.','Válaszd meg, milyen messzire.','Európa','Ázsia','Közel-Kelet','Észak-Amerika','Latin-Amerika','Afrika','Óceánia','Válassz legalább egy indulási repülőteret','A szűrők megváltoztak — nyomd meg a Keresést','Foglalás','Szállás','Programok'],
ro:['Căutare','Metodă','Transparență','Distribuie','Copiat','Zi','Noapte','Platformă','În curând','Aeroporturi de plecare','Destinații','Tarife verificate','Cel mai bun raport','Plecare','Continent','Țară','Aeroport','Toate','Șterge','selectate','Destinație','Oriunde','Rotește globul și atinge o țară','Când','Fereastră de plecare (zile)','Distanță maximă','Buget maxim','Bagaj de cală','Monedă','Limbă','Caută o țară sau un aeroport','Caută','Rute găsite','Sortează după','Rută','Preț','Distanță','Sejur','Scor','Verifică','nopți','dus-întors','pe segment','Direct','Copiază linkul','Niciun tarif cu aceste filtre','Lărgește fereastra sau scoate un filtru','Oriunde din','Arată toate','Înregistrat la','Nu mai alege unde.','Alege cât de departe.','Europa','Asia','Orientul Mijlociu','America de Nord','America Latină','Africa','Oceania','Alege cel puțin un aeroport de plecare','Filtre modificate — apasă Caută','Rezervă','Cazare','Activități'],
el:['Αναζήτηση','Μέθοδος','Διαφάνεια','Κοινοποίηση','Αντιγράφηκε','Ημέρα','Νύχτα','Πλατφόρμα','Σύντομα','Αεροδρόμια αναχώρησης','Προορισμοί','Επαληθευμένοι ναύλοι','Καλύτερη σχέση','Αναχώρηση','Ήπειρος','Χώρα','Αεροδρόμιο','Όλα','Καθαρισμός','επιλεγμένα','Προορισμός','Οπουδήποτε','Γύρισε την υδρόγειο, άγγιξε μια χώρα','Πότε','Παράθυρο αναχώρησης (ημέρες)','Μέγιστη απόσταση','Μέγιστος προϋπολογισμός','Αποσκευή παράδοσης','Νόμισμα','Γλώσσα','Αναζήτηση χώρας ή αεροδρομίου','Αναζήτηση','Διαδρομές που βρέθηκαν','Ταξινόμηση κατά','Διαδρομή','Τιμή','Απόσταση','Διαμονή','Βαθμολογία','Έλεγχος','νύχτες','μετ’ επιστροφής','ανά σκέλος','Απευθείας','Αντιγραφή συνδέσμου','Κανένας ναύλος με αυτά τα φίλτρα','Διεύρυνε το παράθυρο ή αφαίρεσε ένα φίλτρο','Οπουδήποτε από','Εμφάνιση όλων','Καταγράφηκε','Μη διαλέγεις πού.','Διάλεξε πόσο μακριά.','Ευρώπη','Ασία','Μέση Ανατολή','Βόρεια Αμερική','Λατινική Αμερική','Αφρική','Ωκεανία','Διάλεξε τουλάχιστον ένα αεροδρόμιο αναχώρησης','Τα φίλτρα άλλαξαν — πάτησε Αναζήτηση','Κράτηση','Ξενοδοχεία','Δραστηριότητες'],
bg:['Търсене','Метод','Прозрачност','Сподели','Копирано','Ден','Нощ','Платформа','Очаквайте','Летища на излитане','Дестинации','Проверени цени','Най-добро съотношение','Излитане','Континент','Държава','Летище','Всички','Изчисти','избрани','Дестинация','Навсякъде','Завърти глобуса и докосни държава','Кога','Прозорец на излитане (дни)','Максимално разстояние','Максимален бюджет','Чекиран багаж','Валута','Език','Търси държава или летище','Търси','Намерени маршрути','Подреди по','Маршрут','Цена','Разстояние','Престой','Оценка','Провери','нощувки','двупосочно','на отсечка','Директен','Копирай връзката','Няма цена с тези филтри','Разшири прозореца или махни филтър','Навсякъде от','Покажи всички','Отчетено на','Спри да избираш къде.','Избери колко далеч.','Европа','Азия','Близък изток','Северна Америка','Латинска Америка','Африка','Океания','Избери поне едно летище на излитане','Филтрите са променени — натисни Търси','Резервирай','Хотели','Забавления'],
sw:['Tafuta','Mbinu','Uwazi','Shiriki','Imenakiliwa','Mchana','Usiku','Jukwaa','Inakuja','Viwanja vya kuondokea','Marudio','Nauli zilizothibitishwa','Uwiano bora','Kuondoka','Bara','Nchi','Uwanja wa ndege','Zote','Futa','zimechaguliwa','Marudio','Popote','Zungusha dunia, gusa nchi','Lini','Dirisha la kuondoka (siku)','Umbali wa juu','Bajeti ya juu','Mzigo wa kuhifadhiwa','Sarafu','Lugha','Tafuta nchi au uwanja wa ndege','Tafuta','Njia zilizopatikana','Panga kwa','Njia','Bei','Umbali','Kukaa','Alama','Thibitisha','usiku','kwenda na kurudi','kwa safari moja','Moja kwa moja','Nakili kiungo','Hakuna nauli kwa vichujio hivi','Panua dirisha au ondoa kichujio','Popote kutoka','Onyesha zote','Ilirekodiwa','Acha kuchagua wapi.','Chagua umbali gani.','Ulaya','Asia','Mashariki ya Kati','Amerika Kaskazini','Amerika ya Kilatini','Afrika','Oceania','Chagua angalau uwanja mmoja wa kuondokea','Vichujio vimebadilika — bonyeza Tafuta','Weka nafasi','Hoteli','Shughuli'],
tr:['Arama','Yöntem','Şeffaflık','Paylaş','Kopyalandı','Gündüz','Gece','Platform','Yakında','Kalkış havalimanları','Varış noktaları','Doğrulanmış ücretler','En iyi oran','Kalkış','Kıta','Ülke','Havalimanı','Tümü','Temizle','seçili','Varış','Her yere','Küreyi çevir, bir ülkeye dokun','Ne zaman','Kalkış aralığı (gün)','Azami mesafe','Azami bütçe','Kayıtlı bagaj','Para birimi','Dil','Ülke veya havalimanı ara','Ara','Bulunan rotalar','Sırala','Rota','Fiyat','Mesafe','Konaklama','Puan','Doğrula','gece','gidiş-dönüş','tek yön','Direkt','Bağlantıyı kopyala','Bu filtrelerle ücret yok','Aralığı genişlet veya bir filtreyi kaldır','Şuradan her yere:','Tümünü göster','Kayıt tarihi','Nereye sorusunu bırak.','Ne kadar uzağa, onu seç.','Avrupa','Asya','Orta Doğu','Kuzey Amerika','Latin Amerika','Afrika','Okyanusya','En az bir kalkış havalimanı seç','Filtreler değişti — Ara’ya bas','Rezervasyon','Oteller','Aktiviteler'],
ru:['Поиск','Метод','Прозрачность','Поделиться','Скопировано','День','Ночь','Платформа','Скоро','Аэропорты вылета','Направления','Проверенные тарифы','Лучшее соотношение','Вылет','Континент','Страна','Аэропорт','Все','Очистить','выбрано','Направление','Куда угодно','Вращайте глобус, коснитесь страны','Когда','Окно вылета (дней)','Максимальное расстояние','Максимальный бюджет','Багаж','Валюта','Язык','Найти страну или аэропорт','Искать','Найдено маршрутов','Сортировать по','Маршрут','Цена','Расстояние','Пребывание','Оценка','Проверить','ночей','туда и обратно','в одну сторону','Прямой','Копировать ссылку','Нет тарифов с этими фильтрами','Расширьте окно или снимите фильтр','Куда угодно из','Показать все','Зафиксировано','Перестаньте выбирать куда.','Выберите как далеко.','Европа','Азия','Ближний Восток','Северная Америка','Латинская Америка','Африка','Океания','Выберите хотя бы один аэропорт вылета','Фильтры изменены — нажмите «Искать»','Забронировать','Отели','Экскурсии'],
uk:['Пошук','Метод','Прозорість','Поділитися','Скопійовано','День','Ніч','Платформа','Незабаром','Аеропорти вильоту','Напрямки','Перевірені тарифи','Найкраще співвідношення','Виліт','Континент','Країна','Аеропорт','Усі','Очистити','вибрано','Напрямок','Будь-куди','Оберніть глобус, торкніться країни','Коли','Вікно вильоту (днів)','Максимальна відстань','Максимальний бюджет','Багаж','Валюта','Мова','Знайти країну або аеропорт','Шукати','Знайдено маршрутів','Сортувати за','Маршрут','Ціна','Відстань','Перебування','Оцінка','Перевірити','ночей','туди й назад','в один бік','Прямий','Копіювати посилання','Немає тарифів із цими фільтрами','Розширте вікно або зніміть фільтр','Будь-куди з','Показати всі','Зафіксовано','Перестаньте обирати куди.','Оберіть як далеко.','Європа','Азія','Близький Схід','Північна Америка','Латинська Америка','Африка','Океанія','Оберіть хоча б один аеропорт вильоту','Фільтри змінено — натисніть «Шукати»','Забронювати','Готелі','Екскурсії'],
ar:['بحث','المنهج','الشفافية','مشاركة','تم النسخ','نهار','ليل','المنصة','قريباً','مطارات المغادرة','الوجهات','أسعار موثّقة','أفضل نسبة','المغادرة','القارة','الدولة','المطار','الكل','مسح','محدَّد','الوجهة','إلى أي مكان','أدر الكرة الأرضية والمس دولة','متى','نافذة المغادرة (أيام)','أقصى مسافة','أقصى ميزانية','حقيبة مسجّلة','العملة','اللغة','ابحث عن دولة أو مطار','ابحث','المسارات الموجودة','ترتيب حسب','المسار','السعر','المسافة','الإقامة','النقاط','تحقّق','ليالٍ','ذهاب وإياب','لكل اتجاه','مباشر','نسخ الرابط','لا توجد أسعار بهذه الفلاتر','وسّع النافذة أو أزل فلتراً','إلى أي مكان من','عرض الكل','رُصد في','لا تختر إلى أين.','اختر إلى أي مدى.','أوروبا','آسيا','الشرق الأوسط','أمريكا الشمالية','أمريكا اللاتينية','أفريقيا','أوقيانوسيا','اختر مطار مغادرة واحداً على الأقل','تغيّرت الفلاتر — اضغط ابحث','احجز','فنادق','أنشطة'],
he:['חיפוש','שיטה','שקיפות','שיתוף','הועתק','יום','לילה','פלטפורמה','בקרוב','שדות תעופה ליציאה','יעדים','מחירים מאומתים','היחס הטוב ביותר','יציאה','יבשת','מדינה','שדה תעופה','הכול','ניקוי','נבחרו','יעד','לכל מקום','סובב את הגלובוס וגע במדינה','מתי','חלון יציאה (ימים)','מרחק מרבי','תקציב מרבי','מזוודה לבטן המטוס','מטבע','שפה','חפש מדינה או שדה תעופה','חפש','מסלולים שנמצאו','מיין לפי','מסלול','מחיר','מרחק','שהייה','ניקוד','אימות','לילות','הלוך ושוב','לכל כיוון','ישיר','העתק קישור','אין מחיר בפילטרים האלה','הרחב את החלון או הסר פילטר','לכל מקום מ־','הצג הכול','נרשם ב','אל תבחר לאן.','בחר כמה רחוק.','אירופה','אסיה','המזרח התיכון','צפון אמריקה','אמריקה הלטינית','אפריקה','אוקיאניה','בחר לפחות שדה תעופה אחד ליציאה','הפילטרים השתנו — לחץ חפש','הזמנה','מלונות','פעילויות'],
fa:['جستجو','روش','شفافیت','هم‌رسانی','رونوشت شد','روز','شب','سکو','به‌زودی','فرودگاه‌های مبدأ','مقصدها','نرخ‌های تأییدشده','بهترین نسبت','مبدأ','قاره','کشور','فرودگاه','همه','پاک کردن','انتخاب‌شده','مقصد','هر جا','کره را بچرخانید و کشوری را لمس کنید','چه زمانی','بازهٔ پرواز (روز)','بیشترین فاصله','بیشترین بودجه','بار تحویلی','ارز','زبان','کشور یا فرودگاه را جستجو کنید','جستجو','مسیرهای یافت‌شده','مرتب‌سازی بر پایهٔ','مسیر','قیمت','فاصله','اقامت','امتیاز','بررسی','شب','رفت و برگشت','هر مسیر','مستقیم','رونوشت پیوند','با این صافی‌ها نرخی نیست','بازه را بازتر کنید یا صافی را بردارید','هر جا از','نمایش همه','ثبت‌شده در','دیگر «کجا» را انتخاب نکنید.','«چقدر دور» را انتخاب کنید.','اروپا','آسیا','خاورمیانه','آمریکای شمالی','آمریکای لاتین','آفریقا','اقیانوسیه','دست‌کم یک فرودگاه مبدأ انتخاب کنید','صافی‌ها تغییر کرد — جستجو را بزنید','رزرو','هتل‌ها','گشت‌ها'],
ur:['تلاش','طریقہ','شفافیت','شیئر','نقل ہو گیا','دن','رات','پلیٹ فارم','جلد آ رہا ہے','روانگی کے ہوائی اڈے','منزلیں','تصدیق شدہ کرائے','بہترین تناسب','روانگی','براعظم','ملک','ہوائی اڈہ','سب','صاف کریں','منتخب','منزل','کہیں بھی','کرہ گھمائیں، کسی ملک کو چھوئیں','کب','روانگی کی مدت (دن)','زیادہ سے زیادہ فاصلہ','زیادہ سے زیادہ بجٹ','بُک شدہ سامان','کرنسی','زبان','ملک یا ہوائی اڈہ تلاش کریں','تلاش کریں','ملنے والے راستے','ترتیب دیں','راستہ','قیمت','فاصلہ','قیام','اسکور','تصدیق','راتیں','آنا جانا','فی طرف','براہِ راست','لنک نقل کریں','ان فلٹرز پر کوئی کرایہ نہیں','مدت بڑھائیں یا فلٹر ہٹائیں','کہیں بھی، یہاں سے','سب دکھائیں','ریکارڈ کیا گیا','یہ مت چنیں کہ کہاں۔','یہ چنیں کہ کتنی دور۔','یورپ','ایشیا','مشرقِ وسطیٰ','شمالی امریکہ','لاطینی امریکہ','افریقہ','اوقیانوسیہ','کم از کم ایک روانگی کا ہوائی اڈہ منتخب کریں','فلٹرز بدل گئے — تلاش دبائیں','بُک کریں','ہوٹل','سرگرمیاں'],
hi:['खोज','विधि','पारदर्शिता','साझा करें','कॉपी हुआ','दिन','रात','मंच','जल्द आ रहा है','प्रस्थान हवाई अड्डे','गंतव्य','सत्यापित किराए','सर्वोत्तम अनुपात','प्रस्थान','महाद्वीप','देश','हवाई अड्डा','सभी','साफ़ करें','चयनित','गंतव्य','कहीं भी','ग्लोब घुमाएँ, किसी देश को छुएँ','कब','प्रस्थान अवधि (दिन)','अधिकतम दूरी','अधिकतम बजट','चेक किया सामान','मुद्रा','भाषा','देश या हवाई अड्डा खोजें','खोजें','मिले मार्ग','क्रम','मार्ग','कीमत','दूरी','ठहराव','अंक','जाँचें','रातें','आना-जाना','प्रति तरफ़','सीधा','लिंक कॉपी करें','इन फ़िल्टरों पर कोई किराया नहीं','अवधि बढ़ाएँ या फ़िल्टर हटाएँ','कहीं भी, यहाँ से','सभी दिखाएँ','दर्ज किया गया','कहाँ चुनना छोड़िए।','कितनी दूर, वह चुनिए।','यूरोप','एशिया','मध्य पूर्व','उत्तर अमेरिका','लैटिन अमेरिका','अफ़्रीका','ओशिनिया','कम से कम एक प्रस्थान हवाई अड्डा चुनें','फ़िल्टर बदले — खोजें दबाएँ','बुक करें','होटल','गतिविधियाँ'],
bn:['খোঁজ','পদ্ধতি','স্বচ্ছতা','ভাগ করুন','কপি হয়েছে','দিন','রাত','প্ল্যাটফর্ম','শীঘ্রই আসছে','ছাড়ার বিমানবন্দর','গন্তব্য','যাচাই করা ভাড়া','সেরা অনুপাত','ছাড়া','মহাদেশ','দেশ','বিমানবন্দর','সব','মুছুন','নির্বাচিত','গন্তব্য','যেকোনো জায়গায়','গ্লোব ঘোরান, একটি দেশ ছুঁন','কখন','ছাড়ার সময়সীমা (দিন)','সর্বোচ্চ দূরত্ব','সর্বোচ্চ বাজেট','চেক করা ব্যাগ','মুদ্রা','ভাষা','দেশ বা বিমানবন্দর খুঁজুন','খুঁজুন','পাওয়া রুট','সাজান','রুট','দাম','দূরত্ব','অবস্থান','স্কোর','যাচাই','রাত','যাওয়া-আসা','প্রতি পথে','সরাসরি','লিংক কপি করুন','এই ফিল্টারে কোনো ভাড়া নেই','সময়সীমা বাড়ান বা ফিল্টার সরান','যেকোনো জায়গায়, এখান থেকে','সব দেখান','রেকর্ড করা','কোথায়, তা বাছা ছাড়ুন।','কত দূর, তা বাছুন।','ইউরোপ','এশিয়া','মধ্যপ্রাচ্য','উত্তর আমেরিকা','লাতিন আমেরিকা','আফ্রিকা','ওশেনিয়া','অন্তত একটি ছাড়ার বিমানবন্দর বেছে নিন','ফিল্টার বদলেছে — খুঁজুন চাপুন','বুক করুন','হোটেল','অ্যাক্টিভিটি'],
ta:['தேடல்','முறை','வெளிப்படைத்தன்மை','பகிர்','நகலெடுக்கப்பட்டது','பகல்','இரவு','தளம்','விரைவில்','புறப்படும் விமான நிலையங்கள்','சேருமிடங்கள்','சரிபார்க்கப்பட்ட கட்டணங்கள்','சிறந்த விகிதம்','புறப்பாடு','கண்டம்','நாடு','விமான நிலையம்','அனைத்தும்','அழி','தேர்ந்தெடுக்கப்பட்டவை','சேருமிடம்','எங்கும்','உலகக் கோளத்தைச் சுழற்றி ஒரு நாட்டைத் தொடுங்கள்','எப்போது','புறப்பாட்டுக் காலம் (நாட்கள்)','அதிகபட்ச தூரம்','அதிகபட்ச நிதி','ஒப்படைத்த பயணப்பை','நாணயம்','மொழி','நாடு அல்லது விமான நிலையத்தைத் தேடுங்கள்','தேடு','கிடைத்த வழிகள்','வரிசைப்படுத்து','வழி','விலை','தூரம்','தங்கல்','மதிப்பெண்','சரிபார்','இரவுகள்','போக்கு வரத்து','ஒரு பக்கம்','நேரடி','இணைப்பை நகலெடு','இந்த வடிகட்டிகளுக்குக் கட்டணம் இல்லை','காலத்தை விரிவாக்கு அல்லது வடிகட்டியை நீக்கு','இங்கிருந்து எங்கும்','அனைத்தையும் காட்டு','பதிவு செய்யப்பட்டது','எங்கே என்பதைத் தேர்வதை விடுங்கள்.','எவ்வளவு தூரம் என்பதைத் தேர்ந்தெடுங்கள்.','ஐரோப்பா','ஆசியா','மத்திய கிழக்கு','வட அமெரிக்கா','லத்தீன் அமெரிக்கா','ஆப்பிரிக்கா','ஓசியானியா','குறைந்தது ஒரு புறப்பாட்டு விமான நிலையத்தைத் தேர்ந்தெடுங்கள்','வடிகட்டிகள் மாறின — தேடு அழுத்துங்கள்','முன்பதிவு','ஹோட்டல்கள்','அனுபவங்கள்'],
id:['Pencarian','Metode','Transparansi','Bagikan','Tersalin','Siang','Malam','Platform','Segera hadir','Bandara keberangkatan','Tujuan','Tarif terverifikasi','Rasio terbaik','Keberangkatan','Benua','Negara','Bandara','Semua','Hapus','dipilih','Tujuan','Ke mana saja','Putar bola dunia, sentuh sebuah negara','Kapan','Rentang keberangkatan (hari)','Jarak maksimum','Anggaran maksimum','Bagasi tercatat','Mata uang','Bahasa','Cari negara atau bandara','Cari','Rute ditemukan','Urutkan menurut','Rute','Harga','Jarak','Menginap','Skor','Verifikasi','malam','pulang pergi','per rute','Langsung','Salin tautan','Tidak ada tarif dengan filter ini','Perluas rentang atau hapus satu filter','Ke mana saja dari','Tampilkan semua','Dicatat pada','Berhenti memilih ke mana.','Pilih seberapa jauh.','Eropa','Asia','Timur Tengah','Amerika Utara','Amerika Latin','Afrika','Oseania','Pilih minimal satu bandara keberangkatan','Filter berubah — tekan Cari','Pesan','Hotel','Aktivitas'],
ms:['Carian','Kaedah','Ketelusan','Kongsi','Disalin','Siang','Malam','Platform','Akan datang','Lapangan terbang berlepas','Destinasi','Tambang disahkan','Nisbah terbaik','Berlepas','Benua','Negara','Lapangan terbang','Semua','Kosongkan','dipilih','Destinasi','Ke mana sahaja','Putar glob, sentuh sebuah negara','Bila','Tetingkap berlepas (hari)','Jarak maksimum','Belanjawan maksimum','Bagasi berdaftar','Mata wang','Bahasa','Cari negara atau lapangan terbang','Cari','Laluan dijumpai','Susun mengikut','Laluan','Harga','Jarak','Penginapan','Skor','Sahkan','malam','pergi balik','sehala','Terus','Salin pautan','Tiada tambang dengan penapis ini','Luaskan tetingkap atau buang penapis','Ke mana sahaja dari','Tunjuk semua','Direkod pada','Berhenti memilih ke mana.','Pilih sejauh mana.','Eropah','Asia','Timur Tengah','Amerika Utara','Amerika Latin','Afrika','Oceania','Pilih sekurang-kurangnya satu lapangan terbang berlepas','Penapis berubah — tekan Cari','Tempah','Hotel','Aktiviti'],
tl:['Paghahanap','Paraan','Transparensiya','Ibahagi','Nakopya','Araw','Gabi','Plataporma','Malapit nang dumating','Mga paliparan ng alis','Mga destinasyon','Beripikadong pasahe','Pinakamahusay na ratio','Pag-alis','Kontinente','Bansa','Paliparan','Lahat','Burahin','napili','Destinasyon','Kahit saan','Iikot ang globo, pindutin ang bansa','Kailan','Saklaw ng pag-alis (araw)','Pinakamalayong distansya','Pinakamataas na budget','Check-in na bagahe','Salapi','Wika','Maghanap ng bansa o paliparan','Maghanap','Mga rutang natagpuan','Ayusin ayon sa','Ruta','Presyo','Distansya','Pananatili','Iskor','Suriin','gabi','balikan','bawat biyahe','Diretso','Kopyahin ang link','Walang pasaheng tumutugma','Palawakin ang saklaw o mag-alis ng filter','Kahit saan mula sa','Ipakita lahat','Naitala noong','Huwag nang piliin kung saan.','Piliin kung gaano kalayo.','Europa','Asya','Gitnang Silangan','Hilagang Amerika','Latin Amerika','Aprika','Oceania','Pumili ng kahit isang paliparan ng alis','Nabago ang mga filter — pindutin ang Maghanap','Mag-book','Mga hotel','Mga aktibidad'],
vi:['Tìm kiếm','Phương pháp','Minh bạch','Chia sẻ','Đã sao chép','Ngày','Đêm','Nền tảng','Sắp có','Sân bay khởi hành','Điểm đến','Giá vé đã xác minh','Tỉ lệ tốt nhất','Khởi hành','Châu lục','Quốc gia','Sân bay','Tất cả','Xóa','đã chọn','Điểm đến','Bất cứ đâu','Xoay quả cầu, chạm vào một quốc gia','Khi nào','Khoảng khởi hành (ngày)','Khoảng cách tối đa','Ngân sách tối đa','Hành lý ký gửi','Tiền tệ','Ngôn ngữ','Tìm quốc gia hoặc sân bay','Tìm','Tuyến tìm được','Sắp xếp theo','Tuyến','Giá','Khoảng cách','Lưu trú','Điểm','Kiểm tra','đêm','khứ hồi','mỗi chiều','Bay thẳng','Sao chép liên kết','Không có giá vé với bộ lọc này','Mở rộng khoảng hoặc bỏ một bộ lọc','Bất cứ đâu từ','Hiện tất cả','Ghi nhận ngày','Đừng chọn đi đâu nữa.','Hãy chọn đi xa bao nhiêu.','Châu Âu','Châu Á','Trung Đông','Bắc Mỹ','Mỹ Latinh','Châu Phi','Châu Đại Dương','Chọn ít nhất một sân bay khởi hành','Bộ lọc đã đổi — bấm Tìm','Đặt vé','Khách sạn','Hoạt động'],
th:['ค้นหา','วิธีการ','ความโปร่งใส','แชร์','คัดลอกแล้ว','กลางวัน','กลางคืน','แพลตฟอร์ม','เร็ว ๆ นี้','สนามบินต้นทาง','จุดหมาย','ค่าโดยสารที่ตรวจสอบแล้ว','อัตราส่วนดีที่สุด','ออกเดินทาง','ทวีป','ประเทศ','สนามบิน','ทั้งหมด','ล้าง','ที่เลือก','จุดหมาย','ที่ไหนก็ได้','หมุนลูกโลกแล้วแตะประเทศ','เมื่อไร','ช่วงออกเดินทาง (วัน)','ระยะทางสูงสุด','งบประมาณสูงสุด','สัมภาระใต้ท้องเครื่อง','สกุลเงิน','ภาษา','ค้นหาประเทศหรือสนามบิน','ค้นหา','เส้นทางที่พบ','เรียงตาม','เส้นทาง','ราคา','ระยะทาง','การพัก','คะแนน','ตรวจสอบ','คืน','ไป-กลับ','ต่อเที่ยว','บินตรง','คัดลอกลิงก์','ไม่มีค่าโดยสารตามตัวกรองนี้','ขยายช่วงเวลาหรือเอาตัวกรองออก','ที่ไหนก็ได้จาก','แสดงทั้งหมด','บันทึกเมื่อ','เลิกเลือกว่าจะไปที่ไหน','เลือกว่าจะไปไกลแค่ไหน','ยุโรป','เอเชีย','ตะวันออกกลาง','อเมริกาเหนือ','ละตินอเมริกา','แอฟริกา','โอเชียเนีย','เลือกสนามบินต้นทางอย่างน้อยหนึ่งแห่ง','ตัวกรองเปลี่ยนแล้ว — กดค้นหา','จอง','โรงแรม','กิจกรรม'],
zh:['搜索','方法','透明度','分享','已复制','日间','夜间','平台','即将推出','出发机场','目的地','已核实票价','最佳性价比','出发','大洲','国家','机场','全部','清除','已选','目的地','任意地点','转动地球，点击国家','时间','出发窗口（天）','最大距离','最高预算','托运行李','货币','语言','搜索国家或机场','搜索','找到的航线','排序方式','航线','价格','距离','停留','评分','核实','晚','往返','单程','直飞','复制链接','该筛选条件下没有票价','放宽时间窗口或去掉一个筛选','任意地点，出发自','显示全部','记录于','别再选去哪里。','选择要走多远。','欧洲','亚洲','中东','北美洲','拉丁美洲','非洲','大洋洲','至少选择一个出发机场','筛选条件已更改 — 请点击搜索','预订','酒店','玩乐'],
ja:['検索','方法','透明性','共有','コピーしました','昼','夜','プラットフォーム','近日公開','出発空港','目的地','検証済み運賃','最良の比率','出発','大陸','国','空港','すべて','クリア','選択済み','目的地','どこへでも','地球儀を回して国をタップ','いつ','出発ウィンドウ（日）','最大距離','最大予算','受託手荷物','通貨','言語','国または空港を検索','検索','見つかった路線','並べ替え','路線','価格','距離','滞在','スコア','確認','泊','往復','片道あたり','直行','リンクをコピー','この条件に合う運賃はありません','期間を広げるかフィルターを外してください','ここからどこへでも','すべて表示','取得日','どこへ行くかを選ぶのはやめよう。','どこまで行くかを選ぼう。','ヨーロッパ','アジア','中東','北アメリカ','ラテンアメリカ','アフリカ','オセアニア','出発空港を少なくとも一つ選んでください','条件が変わりました — 検索を押してください','予約','ホテル','アクティビティ'],
ko:['검색','방법','투명성','공유','복사됨','주간','야간','플랫폼','출시 예정','출발 공항','목적지','검증된 운임','최고 비율','출발','대륙','국가','공항','전체','지우기','선택됨','목적지','어디든지','지구본을 돌려 국가를 누르세요','언제','출발 기간(일)','최대 거리','최대 예산','위탁 수하물','통화','언어','국가 또는 공항 검색','검색','찾은 노선','정렬 기준','노선','가격','거리','체류','점수','확인','박','왕복','편도당','직항','링크 복사','이 필터에 맞는 운임이 없습니다','기간을 넓히거나 필터를 해제하세요','여기에서 어디든지','전체 보기','기록일','어디로 갈지 고르지 마세요.','얼마나 멀리 갈지 고르세요.','유럽','아시아','중동','북아메리카','라틴 아메리카','아프리카','오세아니아','출발 공항을 하나 이상 선택하세요','조건이 바뀌었습니다 — 검색을 누르세요','예약','호텔','액티비티'],
};

/* lingue offerte, con il nome nella lingua stessa (endonimo) e il verso */
const LANG_META = [
 ['en','English'],['zh','中文'],['hi','हिन्दी'],['es','Español'],['ar','العربية',1],['fr','Français'],
 ['bn','বাংলা'],['pt','Português'],['ru','Русский'],['ur','اردو',1],['id','Bahasa Indonesia'],
 ['de','Deutsch'],['ja','日本語'],['tr','Türkçe'],['ko','한국어'],['vi','Tiếng Việt'],['it','Italiano'],
 ['fa','فارسی',1],['th','ไทย'],['pl','Polski'],['nl','Nederlands'],['uk','Українська'],['ro','Română'],
 ['el','Ελληνικά'],['cs','Čeština'],['sv','Svenska'],['hu','Magyar'],['he','עברית',1],
 ['ms','Bahasa Melayu'],['ta','தமிழ்'],['sw','Kiswahili'],['da','Dansk'],['no','Norsk'],['fi','Suomi'],
 ['bg','Български'],['tl','Filipino'],
];

/* ── valute ───────────────────────────────────────────────────────────
   [codice, simbolo, decimali, unita' per 1 EUR].
   I cambi sono una fotografia datata: servono a rendere leggibile un
   prezzo, non a fare cassa. Il prezzo su cui si prenota resta quello
   dell'operatore. Quando la modalita' live e' attiva i prezzi arrivano
   gia' convertiti dalla fonte e questa tabella non viene usata.        */
const FX_DATE = '2026-09-02';
const CUR = [
 ['EUR','€',0,1],            ['USD','$',0,1.1594],       ['GBP','£',0,0.8572],
 ['CHF','CHF',0,0.9408],     ['JPY','¥',0,185.64],       ['CNY','¥',0,7.8063],
 ['AUD','A$',0,1.6219],      ['CAD','C$',0,1.6104],      ['SGD','S$',0,1.4761],
 ['HKD','HK$',0,9.0902],     ['KRW','₩',0,1593.05],      ['INR','₹',0,110.09],
 ['AED','AED',0,4.2579],     ['SAR','SAR',0,4.3478],     ['QAR','QAR',0,4.2202],
 ['KWD','KWD',2,0.3581],     ['BHD','BHD',2,0.4359],     ['OMR','OMR',2,0.4458],
 ['JOD','JOD',2,0.8220],     ['ILS','₪',0,3.5090],       ['TRY','₺',0,55.978],
 ['EGP','EGP',0,58.959],     ['MAD','MAD',0,10.809],     ['TND','TND',2,3.3786],
 ['ZAR','R',0,18.731],       ['NGN','₦',0,1567.19],      ['KES','KSh',0,150.15],
 ['ETB','ETB',0,189.72],     ['MUR','MUR',0,54.569],     ['THB','฿',0,38.570],
 ['VND','₫',0,30036.9],      ['IDR','Rp',0,20582.0],     ['MYR','RM',0,4.6823],
 ['PHP','₱',0,72.341],       ['TWD','NT$',0,36.743],     ['PKR','Rs',0,322.15],
 ['BDT','৳',0,142.26],       ['KZT','₸',0,531.00],       ['AZN','₼',0,1.9710],
 ['GEL','₾',0,3.0368],       ['AMD','֏',0,422.34],       ['UAH','₴',0,51.525],
 ['RSD','RSD',0,117.33],     ['BGN','лв',0,1.9558],      ['RON','lei',0,5.2568],
 ['PLN','zł',0,4.3328],      ['CZK','Kč',0,24.179],      ['HUF','Ft',0,367.27],
 ['SEK','kr',0,11.141],      ['NOK','kr',0,10.815],      ['DKK','kr',0,7.4746],
 ['ISK','kr',0,140.71],      ['BRL','R$',0,6.0007],      ['MXN','MX$',0,19.697],
 ['ARS','ARS',0,1753.87],    ['CLP','CLP',0,1083.55],    ['COP','COP',0,3725.45],
 ['PEN','S/',0,3.8996],      ['NZD','NZ$',0,1.9666],
];
